### PR TITLE
fix(aws-amplify-react): use <form/> for the login component

### LINKED ISSUE #2791: React: SignIn captures global keydown event to submit form
**Describe the bug**
The SignIn form registers a [global event handler for `keydown`](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/SignIn.jsx#L53). The handler checks whether `[enter]` was pressed and then submits the form.

However, the event handler is triggered when `[enter]` is pressed _anywhere_ on the page, even in another form. That means when a user presses enter on a page where the sign-in dialog is visible, they always get a very prominent error message that the sign in has failed.

**To Reproduce**
1. Create a page where there's a regular `<form>` with an `<input>` plus an `<Authenticator>`
2. Focus the regular input and press enter --> the sign-in-form will produce an error.

**Expected behavior**
The sign-in form should instead use a regular `<form onSubmit={...}>`. The submit button then doesn't need an `onClick` handler but simply becomes `type="submit"` and hence triggers the form submit. That's what forms are for after all. No need to reinvent anything.

I'd be happy to contribute a PR if you like.

### PR DESCRIPTION
**Pull request by powerful23**
*Issue #, if available:*
fixes #2791 
*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by haverchuck** [comment]
I believe that sign in is the only component that is having the event problem (I checking signup and a couple of others) - have you confirmed that?

File: packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx [hunk 1]
```diff
@@ -28,6 +28,16 @@ export const FormContainer = (props) => {
     );
 };
 
+// currently just a wrapper of the web form
+export const WebForm = (props) => {
+    const theme = props.theme || AmplifyTheme;
+    return beforeAfter(
```
Comment (alebiavati) [inline packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx]: I think we should not allow to apply a theme to the `form` element as it's used for functionality only, not styles. We can just use the `form` element directly without wrapping it in a component.

**Comment by powerful23** [comment]
@haverchuck 
> You confirmed that sign in is the only affected component (I believe it is)? Should we go ahead and add the form to all of them, even though the bug is primarily for the one component?

The plan is we fix the signIn component for now and apply this change to all in the UI component refactor.

File: packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx (hunk 1 above)
Comment (powerful23) [reply packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx]: Make sense. Has removed that part.

File: packages/aws-amplify-react/src/Auth/SignIn.jsx [hunk 2]
```diff
@@ -124,6 +110,7 @@ export default class SignIn extends AuthPiece {
         const hideForgotPassword = !override.includes('ForgotPassword') && hide.some(component => component === ForgotPassword);
         return (
             <FormSection theme={theme}>
+                <WebForm onSubmit={this.signIn}>
```
Comment (jordanranz) [inline packages/aws-amplify-react/src/Auth/SignIn.jsx]: Is there a reason we can't just use <form> here?

Comment (powerful23) [reply packages/aws-amplify-react/src/Auth/SignIn.jsx]: Well we can use it here. I just want to keep the style like all the Components are React components.

Comment (alebiavati) [reply packages/aws-amplify-react/src/Auth/SignIn.jsx]: I think `WebForm` should be avoided altogether. UI components should only be used to add styles. We should not wrap `form` element because it only adds functionality.

Comment (powerful23) [reply packages/aws-amplify-react/src/Auth/SignIn.jsx]: Make sense. I have removed that component and directly use form in the signIn component.
