### PR TITLE
fixes #4219 Readd the variable declaration allDiagnostics

### LINKED ISSUE #4219: ./scripts/build.js/tsc() function will always fail due to undefined symbol `allDiagnostics`
**Describe the bug**
#4007 added a new [./scripts/build.js](https://github.com/aws-amplify/amplify-js/blob/94b7181d0c37fa9dbfaec8d09b93c0c9f1246ec3/scripts/build.js#L62) file with a `tsc()` function.  This function will always throw because `allDiagnostics` is always undefined. In fact there's no other place in the amplify-js codebase where this symbol is used.

https://github.com/aws-amplify/amplify-js/blob/94b7181d0c37fa9dbfaec8d09b93c0c9f1246ec3/scripts/build.js#L62

**To Reproduce**
I was able to repro this last night by just running `yarn run build`.  But before filing this issue I wanted to verify on a clean dev environment so I ran `yarn run clean` and tried a build again and got no errors. So clearly something was corrupted somewhere in my original dev environment. I'm not sure why my previous environment ended up calling `tsc()` but a clean one didn't.

That said, this `tsc()` function will always throw if it's run, so either this is unused code that should be removed, or this code will need to be fixed.

### PR DESCRIPTION
**Pull request by Amplifiyer**
_Issue #, if available:_#4219

_Description of changes:_Readd the variable declaration allDiagnostics

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: scripts/build.js [hunk 1]
```diff
@@ -59,6 +59,10 @@ function tsc(fileNames, options) {
 	let program = ts.createProgram(fileNames, options);
 	let emitResult = program.emit();
 
+	let allDiagnostics = ts
```
Comment (sammartinez) [inline scripts/build.js]: Do we need to add a unit test for this?

Comment (Amplifiyer) [reply scripts/build.js]: good point. Currently we don't have any test coverage for these scritps. I'll create a backlog for back-filling the tests.

**Comment by justingrant** [comment]
Thanks @Amplifiyer for the quick turnaround! BTW if you're thinking about build issues right now, any chance you'd want to review my latest PR #4216? :-)
