### PR TITLE
fix(@aws-amplify/pubsub): catch and throw the error when subscribing using Mqtt

### LINKED ISSUE #2610: "AMQJS0007E Socket error:undefined" on wifi connection loss while trying to subscribe for topics
**Describe the bug**
I am trying to simulate a sudden connection loss, in between query and subscribe.
Even though adding a `try/catch` block for `subscribe()`, still there's an unhandled promise rejection.

**To Reproduce**
Using an iOS simulator, after all query operations are successful, disconnect simulator from WiFi connection.

**Expected behavior**
Since there was a network loss after query AND before or during the subscription process, observable's  `error` callback should be able to handle this socket connection error.

**Screenshots**
screen shot 2019-01-28 at 4 29 35 pm

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari
 - Version 12.0.2

**Smartphone (please complete the following information):**
 - Device: iPhone 8 simulator
 - OS: iOS 12

**Additional context**
I am using React Native. Using iPhone 8 simulator with debug mode enabled.

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

screen shot 2019-01-28 at 4 49 35 pm

### LINKED ISSUE #3212: Subscriptions do not throw error on websocket failure
**Describe the bug**
When subscribing to AppSync updates through AWS Amplify, `undefined` websocket errors do not invoke the `error` callback. If a websocket is unable to connect and returns `undefined`, an error is logged in the console but the subscription's error callback is not invoked.

**To Reproduce**
This occurs when the webapp is connected to a network that blocks or inhibits websocket connections, such as some proxies and corporate networks.

**Expected behavior**
When an error occurs such as a network disconnection, the `error` callback should be invoked. Currently a network disconnection invokes the `error` callback but an `undefined` websocket connection does not.

**Desktop:**
 - OS: Windows 7, Windows 10, and MacOS X
 - Browser: Chrome 73, IE 11, and Edge 15

**Smartphone:**
 - Device: iPhone X
 - OS: iOS 12.2
 - Browser: Safari

**Sample code**
```
API.graphql(
  graphqlOperation(subscriptions.mutatedItem, { item_id: item_id })
).subscribe({
  error: (err) => console.log("Network disconnected"),
  next: (eventData) => updateItems(eventData)
});
```

***Console Output***
> paho-mqtt.js:1128 WebSocket connection to 'wss://**************-ats.iot.us-west-2.amazonaws.com/mqtt?...' failed: Error during WebSocket handshake: Unexpected response code: 400
> S._doConnect @ paho-mqtt.js:1128

> Uncaught (in promise)
> Object
> errorCode: 7
> errorMessage: "AMQJS0007E Socket error:undefined."
> invocationContext: undefined

### PR DESCRIPTION
**Pull request by powerful23**
*Issue #, if available:*
fixes #3212 
fixes #2610 
*Description of changes:*
The unhandled promise rejection is generated in: https://github.com/aws-amplify/amplify-js/blob/47c7cfdd6308b14a1f7673e339680021c2a8764f/packages/pubsub/src/Providers/MqttOverWSProvider.ts#L185-L192

By catching that error and throw it by `observer.error`, it now will be caught when calling `subscribe()`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/pubsub/__tests__/PubSub-unit-test.ts [hunk 1]
```diff
@@ -195,6 +195,31 @@ describe('PubSub', () => {
...
+                aws_pubsub_region: 'region',
+                aws_pubsub_endpoint: 'wss://iot.mymockendpoint.org:443/notrealmqtt'
+            });
+            pubsub.addPluggable(awsIotProvider);
+
+            jest.spyOn(MqttOverWSProvider.prototype, 'connect').mockImplementationOnce(() => {
+                return Promise.reject('Failed to connect to the network');
+            });
+
+            expect.assertions(1);
```
Comment (manueliglesias) [inline packages/pubsub/__tests__/PubSub-unit-test.ts]: Instead of specifying the number of expected assertions, it is better to use jest's `.rejects`, see example:

```js
const testPubSubAsync = async () => {
  throw new Error('Some error');
}

describe('error testing', () => {
  it('should throw an error', () => {
    expect(testPubSubAsync('some', 'params'))
      .rejects.toThrowError('Some error')
  });
});
```

With this pattern, you don't have to update the number of expected assertions if you add more.

**Note that your test might no longer need the `async` keyword**

Please update both tests to this form.
