### PR TITLE
Aws amplify react fix

### LINKED ISSUE #1539: withAuthenticator HOC does not accept phone number in format matching input's placeholder value
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
When I'm using the withAuthenticator HOC, the phone number's placeholder text shows a phone number in the format of '555-555-1212'.  If I enter a phone number in that format, I get an error which seems to be that it doesn't like the hypens in the input, and it does indeed work if I remove the hyphens from my phone number format. See screenshots below.

What is the expected behavior?
I expect to be able to enter a phone number matching the placeholder format shown to me.

Which versions of Amplify, and which browser / OS are affected by this issue? 
aws-amplify-react 2.0.0

Placeholders
image

With data entered matching placeholder formats
image

### LINKED ISSUE #1641: <PhotoPicker preview="hidden" /> does not work
**Describe the bug**
the ```preview``` prop in ```<PhotoPicker preview="hidden" />``` does not work

**To Reproduce**
1. Go to https://aws-amplify.github.io/amplify-js/media/storage_guide#picker
2. follow instructions to install and use this component

**Expected behavior**
the preview is hidden after setting the ```preview="hidden"``` prop

**Desktop (please complete the following information):**
 - OS: osx
 - Browser chrome, safari

### PR DESCRIPTION
**Pull request by powerful23**
*Issue #, if available:*
fixes #1641 
fixes #1539 
*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/aws-amplify-react/src/Auth/SignUp.jsx [hunk 1]
```diff
@@ -51,9 +51,12 @@ export default class SignUp extends AuthPiece {
             throw new Error('No Auth module found, please ensure @aws-amplify/auth is imported');
         }
 
-        let phone_number = null;
-        if (dial_code && phone_line_number) {
-            phone_number = dial_code + phone_line_number;
+        let phone_number = phone_line_number? '': null;
+        if (phone_line_number) {
+            phone_line_number.split('-').forEach(num => {
```
Comment (yuth) [inline packages/aws-amplify-react/src/Auth/SignUp.jsx]: Instead of looping we should use regex replace
```javascript
phone_line_number.replace(/[-()]/g, '')
```

File: packages/aws-amplify-react/src/Auth/SignUp.jsx [hunk 2]
```diff
@@ -51,9 +51,12 @@ export default class SignUp extends AuthPiece {
...
+                phone_number += num;
+            });
+            if (dial_code) phone_number = dial_code + phone_number;
```
Comment (yuth) [inline packages/aws-amplify-react/src/Auth/SignUp.jsx]:
```javascript
phone_number = `${dial_code}${phone_number}`;
```
