### PR TITLE
fix(#2301)

### LINKED ISSUE #2301: ResourceNotFoundException after deleting anonymous identity from Cognito.
My Expo/React Native app supports both signed-in and anonymous users.  I have this code to get the user's IdentityId:

        const userCredentials = await Auth.currentUserCredentials();
        const id = userCredentials.data.IdentityId;
        let name = "anonymous";

        if (userCredentials.authenticated) {
          const userInfo = await Auth.currentUserInfo();
          name = userInfo.attributes.email;
        }

This works fine and I've been using it to test my Expo app (expo v31.0.4) on the iOS Simulator.  So here are the steps that caused the problem:

1. Open a browser and login to AWS.
2. Go to Cognito/Manage Identity Pools.
3. Select your identity pool.
4. Click the "Identity browser" menu item on the left.
5. Select the anonymous user with the same ID created by the iOS Simulator. 
6. Click the "Delete identity" button on that page.

So I deleted the identity, but in theory this shouldn't be an issue.  It's just the anonymous identity -- my expectation is that Amplify will just recreate it if it doesn't exist. But it doesn't. Instead the above code throws an exception when I call Auth.currentUserCredentials():

**ResourceNotFoundException: Identity 'us-west-2:b3149f7c-57a8-480b-a97d-95e6582ca370' not found.**

Here are some [DEBUG] lines:
```
[DEBUG] 29:20.721 AuthClass - Getting current user credentials
[DEBUG] 29:20.722 AuthClass - failed to get or parse item aws-amplify-federatedInfo SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at AuthClass.currentUserCredentials (blob:http://127.0.0.1:19001/ff59e96d-d7ba-48a6-8508-2a1cc23b2bbd:183830:30)
    at App.componentWillMount$ (blob:http://127.0.0.1:19001/ff59e96d-d7ba-48a6-8508-2a1cc23b2bbd:144677:68)
    at tryCatch (blob:http://127.0.0.1:19001/ff59e96d-d7ba-48a6-8508-2a1cc23b2bbd:21886:19)
    at Generator.invoke [as _invoke] (blob:http://127.0.0.1:19001/ff59e96d-d7ba-48a6-8508-2a1cc23b2bbd:22061:24)
    at Generator.prototype.(anonymous function) [as next] (blob:http://127.0.0.1:19001/ff59e96d-d7ba-48a6-8508-2a1cc23b2bbd:21929:23)
    at tryCatch (blob:http://127.0.0.1:19001/ff59e96d-d7ba-48a6-8508-2a1cc23b2bbd:21886:19)
    at invoke (blob:http://127.0.0.1:19001/ff59e96d-d7ba-48a6-8508-2a1cc23b2bbd:21962:22)
    at blob:http://127.0.0.1:19001/ff59e96d-d7ba-48a6-8508-2a1cc23b2bbd:21992:13
    at tryCallTwo (blob:http://127.0.0.1:19001/ff59e96d-d7ba-48a6-8508-2a1cc23b2bbd:4209:7)
[DEBUG] 29:20.727 AuthClass - Getting current session
[DEBUG] 29:22.443 AuthClass - Failed to get user from user pool
[DEBUG] 29:22.446 AuthClass - Failed to get the current user No current user
[DEBUG] 29:22.449 AuthClass - getting session failed No current user
[DEBUG] 29:22.451 Credentials - setting credentials for guest
[DEBUG] 29:22.802 Credentials - Failed to load credentials 
[DEBUG] 29:22.819 Credentials - Failed to load credentials CognitoIdentityCredentials {expired: true, expireTime: null, accessKeyId: undefined, sessionToken: undefined, params: {…}, …}
[DEBUG] 21:22.195 AWSPinpointProvider - ensure credentials error Error: Identity 'us-west-2:b3149f7c-57a8-480b-a97d-95e6582ca370' not found.
    at Request.extractError (aws-sdk-core-react-native.js:1854)
    at Request.callListeners (aws-sdk-core-react-native.js:3610)
    at Request.emit (aws-sdk-core-react-native.js:3582)
    at Request.emit (aws-sdk-core-react-native.js:7723)
    at Request.transition (aws-sdk-core-react-native.js:7062)
    at AcceptorStateMachine.runTo (aws-sdk-core-react-native.js:7867)
    at aws-sdk-core-react-native.js:7879
    at Request.<anonymous> (aws-sdk-core-react-native.js:7078)
    at Request.<anonymous> (aws-sdk-core-react-native.js:7725)
    at Request.callListeners (aws-sdk-core-react-native.js:3620)
[DEBUG] 29:22.826 AWSPinpointProvider - cannot send events without credentials, applicationId or region
```
What's the solution to this problem?

Thanks,
Alvaro

### PR DESCRIPTION
**Pull request by haverchuck**
*Issue #, if available:*
Fixes #2301 

*Description of changes:*
Adds error handling in setCredentialsForGuest to handle deleted identity ID.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/core/src/Credentials.ts [hunk 1]
```diff
@@ -170,7 +171,35 @@ export class Credentials {
...
+            // If identity id is deleted in the console, we make one attempt to recreate it
+            // and remove existing id from cache. 
+            if (e.code === 'ResourceNotFoundException' &&
+                e.message === `Identity '${identityId}' not found.`
+                && !attempted) {
+                attempted = true;
+                logger.debug('Failed to load guest credentials');
+                this._storage.removeItem('CognitoIdentityId-' + identityPoolId);
+                credentials.clearCachedId();
+                this._storage.removeItem('aws.cognito.identity-id.' + identityPoolId);
```
Comment (AllanFly120) [inline packages/core/src/Credentials.ts]: Is this removing the cache from local storage? I think this is duplicated since`credentials.clearCachedId()` has done the removal. The `'CognitoIdentityId-' + identityPoolId` key is not set by SDK, is it set somewhere by Amplify?
