### PR TITLE
Avoid throwing error when passing sessionStorage to the Auth config

### LINKED ISSUE #3284: using window.sessionStorage as auth storage broken
**Describe the bug**

if you create a angular project using aws-amplify-angular for cognito authentication, and you try to set the storage to window.sessionStorage, you get an error "The storage in the auth config cannot be empty!"

**To Reproduce**

1. take a working angular project using aws-amplify-angular for cognito oauth singin.
2. in the auth config, add:
storage: window.sessionStorage,
3. get error

**Expected behavior**

the amplify framework should sessionStorage for storing tokens instead of localStorage

**Screenshots**
Screenshot (285)
Screenshot (287)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Lubuntu 18.04 LTS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 74

**Additional context**

I believe this is a side effect of https://github.com/aws-amplify/amplify-js/pull/3026

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

### PR DESCRIPTION
**Pull request by powerful23**
*Issue #, if available:*
fixes #3284 
*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/auth/src/Auth.ts [hunk 1]
```diff
@@ -1645,4 +1645,13 @@ export default class AuthClass {
         }
         return user;
     }
+
+    private _isValidAuthStorage(obj) {
+        return obj !== undefined &&
+            obj !== null &&
```
Comment (haverchuck) [inline packages/auth/src/Auth.ts]: instead of
```
obj !== undefined &&
obj !== null
```
could you just do `!!obj`?
