### PR TITLE
fix(@aws-amplify/ui-components): display friendly error for empty password

### LINKED ISSUE #5623: Custom auth lambda trigger is not configured for the user pool.
**Describe the bug**

Using the Vue.js `<amplify-sign-in>` component, when attempting to log in with a blank password, I get the error "Custom auth lambda trigger is not configured for the user pool."

image

**To Reproduce**

Configure a Cognito user pool with just the email attribute required, and the OAuth 2.0 Authorization code grant flow. Scopes set to `'email', 'profile', 'openid'`.

**Expected behavior**

An error message like "password is required". Ideally, the form wouldn't even submit.

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**Screenshots**

**What is Configured?**

Manual configuration:

```
const config = {
  Auth: {
    region: 'us-east-1',
    userPoolId: 'us-east-1_xxxxx', 
    userPoolWebClientId: 'xxxxxxxxxxxx',
    oauth: {
      scope: ['email', 'profile', 'openid'],
      redirectSignIn: 'http://localhost:8080',
      redirectSignOut: 'http://localhost:8080',
      responseType: 'code',
    },
  },
  Storage: {
    AWSS3: {
      bucket: 'xxxxxxxx',
      region: 'us-east-1',
    },
  },
};

export default config;
```

```
aws cognito-idp describe-user-pool --user-pool-id us-east-1_Nqtk7VOG7
{
    "UserPool": {
        "Id": "us-east-1_xxxxxxxxxxx",
        "Name": "xxxxxxxxx-UserPool",
        "Policies": {
            "PasswordPolicy": {
                "MinimumLength": 8,
                "RequireUppercase": false,
                "RequireLowercase": false,
                "RequireNumbers": false,
                "RequireSymbols": false,
                "TemporaryPasswordValidityDays": 7
            }
        },
        "LambdaConfig": {},
        "LastModifiedDate": 1586972919.04,
        "CreationDate": 1586950658.697,
        "SchemaAttributes": [
            {
                "Name": "sub",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": false,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "1",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "given_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "family_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "middle_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "nickname",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "preferred_username",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "profile",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "picture",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "website",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": false,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "gender",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "10",
                    "MaxLength": "10"
                }
            },
            {
                "Name": "zoneinfo",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "locale",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "address",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "updated_at",
                "AttributeDataType": "Number",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "NumberAttributeConstraints": {
                    "MinValue": "0"
                }
            }
        ],
        "AutoVerifiedAttributes": [
            "email"
        ],
        "UsernameAttributes": [
            "email"
        ],
        "VerificationMessageTemplate": {
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "MfaConfiguration": "OFF",
        "EstimatedNumberOfUsers": 2,
        "EmailConfiguration": {
            "EmailSendingAccount": "COGNITO_DEFAULT"
        },
        "UserPoolTags": {},
        "Domain": "xxxxxxxxxx",
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": true,
            "UnusedAccountValidityDays": 7
        },
        "Arn": "arn:aws:cognito-idp:us-east-1:123456798012:userpool/us-east-1_xxxxxxxx"
    }
}
```

### PR DESCRIPTION
**Pull request by wlee221**
_Issue #, if available:_ Fixes #5623 

_Description of changes:_ Displays "password cannot be empty" message on sign in attempts without a password, if custom lambda triggers are not configured.

**Problem**
If `password` is empty on `Auth.signIn()`, `Auth` assumes that the client is on a custom auth flow with lambda triggers set up. This is not the case for UI users who just forgot to put a password (or mistakenly pressed enter early). They would get "Custom auth lambda trigger is not configured for the user pool." error instead, which is unreadable to end users. 

**Solution**
This PR detects if the error is due to empty password on custom auth flow, and changes the message to "Password cannot be empty" for readability. 

Screen Shot 2020-12-14 at 10 25 02 AM

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-ui-components/src/common/auth-helpers.ts [hunk 1]
```diff
@@ -50,13 +50,16 @@ export const handleSignIn = async (username: string, password: string, handleAut
...
   } catch (error) {
-    dispatchToastHubEvent(error);
     if (error.code === 'UserNotConfirmedException') {
       logger.debug('the user is not confirmed');
       handleAuthStateChange(AuthState.ConfirmSignUp, { username });
     } else if (error.code === 'PasswordResetRequiredException') {
       logger.debug('the user requires a new password');
       handleAuthStateChange(AuthState.ForgotPassword, { username });
+    } else if (error.code === 'InvalidParameterException' && password === '') {
+      logger.debug('Empty password was passed, with no custom auth lambda triggers configured', error);
```
Comment (sammartinez) [inline packages/amplify-ui-components/src/common/auth-helpers.ts:60]: Will this always be the case for this invalid parameter exception to trigger? That it will only be on custom auth lambda triggers?

Comment (wlee221) [reply packages/amplify-ui-components/src/common/auth-helpers.ts:60]: Good point, I'll generalize the message.

**Review by sammartinez — APPROVED** [review]
LGTM 🌮

**Comment by QcPerreault** [comment]
@wlee221 Thanks a lot, but will it be possible to edit this error message throught Translations?

**Comment by wlee221** [comment]
@QcPerreault, thanks for the catch! I made a follow up PR #7403
