### PR TITLE
fix: Update AmazonPersonalizeProvider Analytics typings

### LINKED ISSUE #9943: AmazonPersonalizeProvider is not working with the latest version of packages/analytics/src/Analytics.ts
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Analytics

### Amplify Categories

analytics

### Environment information

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 90.52 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.4
  npmPackages:
    @angular-devkit/build-angular: ~13.2.3 => 13.2.6 
    @angular-eslint/builder: ~13.0.1 => 13.0.1 
    @angular-eslint/eslint-plugin: ~13.0.1 => 13.0.1 
    @angular-eslint/eslint-plugin-template: ~13.0.1 => 13.0.1 
    @angular-eslint/template-parser: ~13.0.1 => 13.0.1 
    @angular/cli: ~13.2.3 => 13.2.6 
    @angular/common: ~13.2.2 => 13.2.7 
    @angular/common/http:  undefined ()
    @angular/common/http/testing:  undefined ()
    @angular/common/testing:  undefined ()
    @angular/common/upgrade:  undefined ()
    @angular/compiler: ~13.2.2 => 13.2.7 
    @angular/compiler-cli: ~13.2.2 => 13.2.7 
    @angular/compiler/testing:  undefined ()
    @angular/core: ~13.2.2 => 13.2.7 
    @angular/core/testing:  undefined ()
    @angular/forms: ~13.2.2 => 13.2.7 
    @angular/language-service: ~13.2.2 => 13.2.7 
    @angular/platform-browser: ~13.2.2 => 13.2.7 
    @angular/platform-browser-dynamic: ~13.2.2 => 13.2.7 
    @angular/platform-browser-dynamic/testing:  undefined ()
    @angular/platform-browser/animations:  undefined ()
    @angular/platform-browser/testing:  undefined ()
    @angular/router: ~13.2.2 => 13.2.7 
    @angular/router/testing:  undefined ()
    @angular/router/upgrade:  undefined ()
    @aws-amplify/ui-angular: ^2.4.7 => 2.4.7 
    @aws-amplify/ui-angular/legacy:  undefined ()
    @capacitor/android: 3.5.1 => 3.5.1 
    @capacitor/app: 1.1.1 => 1.1.1 
    @capacitor/browser: ^1.0.7 => 1.0.7 
    @capacitor/cli: 3.5.1 => 3.5.1 
    @capacitor/core: 3.5.1 => 3.5.1 
    @capacitor/device: ^1.1.2 => 1.1.2 
    @capacitor/haptics: 1.1.4 => 1.1.4 
    @capacitor/ios: 3.5.1 => 3.5.1 
    @capacitor/keyboard: 1.2.2 => 1.2.2 
    @capacitor/status-bar: 1.0.8 => 1.0.8 
    @ionic/angular: ^6.0.0 => 6.1.6 
    @ionic/angular-toolkit: ^6.0.0 => 6.1.0 
    @types/jasmine: ~3.6.0 => 3.6.11 
    @types/jasminewd2: ~2.0.3 => 2.0.10 
    @types/node: ^12.11.1 => 12.20.52 
    @typescript-eslint/eslint-plugin: 5.3.0 => 5.3.0 
    @typescript-eslint/parser: 5.3.0 => 5.3.0 
    aws-amplify: ^4.3.24 => 4.3.24 
    eslint: ^7.6.0 => 7.32.0 
    eslint-plugin-import: 2.22.1 => 2.22.1 
    eslint-plugin-jsdoc: 30.7.6 => 30.7.6 
    eslint-plugin-prefer-arrow: 1.2.2 => 1.2.2 
    example-typescript:  1.0.0 
    jasmine-core: ~3.8.0 => 3.8.0 (2.8.0)
    jasmine-spec-reporter: ~5.0.0 => 5.0.2 
    karma: ~6.3.2 => 6.3.20 
    karma-chrome-launcher: ~3.1.0 => 3.1.1 
    karma-coverage: ~2.0.3 => 2.0.3 
    karma-coverage-coffee-example:  1.0.0 
    karma-coverage-istanbul-reporter: ~3.0.2 => 3.0.3 
    karma-jasmine: ~4.0.0 => 4.0.2 
    karma-jasmine-html-reporter: ^1.5.0 => 1.7.0 
    memo-parser:  0.2.1 
    node-example:  1.0.0 
    protractor: ~7.0.0 => 7.0.0 
    protractor-example:  1.0.0 
    rxjs: ~6.6.0 => 6.6.7 (7.5.5)
    rxjs/ajax:  undefined ()
    rxjs/fetch:  undefined ()
    rxjs/internal-compatibility:  undefined ()
    rxjs/operators:  undefined ()
    rxjs/testing:  undefined ()
    rxjs/webSocket:  undefined ()
    ts-node: ~8.3.0 => 8.3.0 
    tslib: ^2.2.0 => 2.4.0 (2.3.1, 1.14.1)
    typescript: ~4.4.4 => 4.4.4 
    typescript-example:  1.0.0 
    zone-mix:  undefined ()
    zone-node:  undefined ()
    zone-testing:  undefined ()
    zone.js: ~0.11.4 => 0.11.5 
    zone.js/async-test:  undefined ()
    zone.js/async-test.min:  undefined ()
    zone.js/fake-async-test:  undefined ()
    zone.js/fake-async-test.min:  undefined ()
    zone.js/jasmine-patch:  undefined ()
    zone.js/jasmine-patch.min:  undefined ()
    zone.js/long-stack-trace-zone:  undefined ()
    zone.js/long-stack-trace-zone.min:  undefined ()
    zone.js/mocha-patch:  undefined ()
    zone.js/mocha-patch.min:  undefined ()
    zone.js/proxy:  undefined ()
    zone.js/proxy.min:  undefined ()
    zone.js/sync-test:  undefined ()
    zone.js/sync-test.min:  undefined ()
    zone.js/task-tracking:  undefined ()
    zone.js/task-tracking.min:  undefined ()
    zone.js/webapis-media-query:  undefined ()
    zone.js/webapis-media-query.min:  undefined ()
    zone.js/webapis-notification:  undefined ()
    zone.js/webapis-notification.min:  undefined ()
    zone.js/webapis-rtc-peer-connection:  undefined ()
    zone.js/webapis-rtc-peer-connection.min:  undefined ()
    zone.js/webapis-shadydom:  undefined ()
    zone.js/webapis-shadydom.min:  undefined ()
    zone.js/wtf:  undefined ()
    zone.js/wtf.min:  undefined ()
    zone.js/zone-bluebird:  undefined ()
    zone.js/zone-bluebird.min:  undefined ()
    zone.js/zone-error:  undefined ()
    zone.js/zone-error.min:  undefined ()
    zone.js/zone-legacy:  undefined ()
    zone.js/zone-legacy.min:  undefined ()
    zone.js/zone-patch-canvas:  undefined ()
    zone.js/zone-patch-canvas.min:  undefined ()
    zone.js/zone-patch-cordova:  undefined ()
    zone.js/zone-patch-cordova.min:  undefined ()
    zone.js/zone-patch-electron:  undefined ()
    zone.js/zone-patch-electron.min:  undefined ()
    zone.js/zone-patch-fetch:  undefined ()
    zone.js/zone-patch-fetch.min:  undefined ()
    zone.js/zone-patch-jsonp:  undefined ()
    zone.js/zone-patch-jsonp.min:  undefined ()
    zone.js/zone-patch-message-port:  undefined ()
    zone.js/zone-patch-message-port.min:  undefined ()
    zone.js/zone-patch-promise-test:  undefined ()
    zone.js/zone-patch-promise-test.min:  undefined ()
    zone.js/zone-patch-resize-observer:  undefined ()
    zone.js/zone-patch-resize-observer.min:  undefined ()
    zone.js/zone-patch-rxjs:  undefined ()
    zone.js/zone-patch-rxjs-fake-async:  undefined ()
    zone.js/zone-patch-rxjs-fake-async.min:  undefined ()
    zone.js/zone-patch-rxjs.min:  undefined ()
    zone.js/zone-patch-socket-io:  undefined ()
    zone.js/zone-patch-socket-io.min:  undefined ()
    zone.js/zone-patch-user-media:  undefined ()
    zone.js/zone-patch-user-media.min:  undefined ()
  npmGlobalPackages:
    @angular/cli: 10.0.2
    @aws-amplify/cli: 7.6.21
    @ionic/cli: 6.18.1
    cordova-res: 0.15.1
    corepack: 0.10.0
    native-run: 1.0.0
    npm: 8.3.1

### Describe the bug

After upgrading aws-amplify to version 4.3.24 the functionaries in this document is not working anymore:
https://docs.amplify.aws/lib/analytics/personalize/q/platform/js/

There will be compile error when trying to use the "record" method:
Screenshot 2022-05-27 at 4 27 11 PM

Screenshot 2022-05-27 at 4 25 14 PM

### Expected behavior

As described in this document, should be able to call Analytics.record with AmazonPersonalize provider.
It works before this update :  https://github.com/aws-amplify/amplify-js/commit/9a52c2b6a59bf0d9622a2572f8752b7b419c0817

### Reproduction steps

https://docs.amplify.aws/lib/analytics/personalize/q/platform/js/

### Code Snippet

Screenshot 2022-05-27 at 4 27 11 PM

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

_No response_

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by jamesaucode**
#### Description of changes
Added types for `event` for 'AmazonPersonalize' provider

#### Issue #, if available
fixes #9943

#### Description of how you validated changes
`yarn build && yarn test`
Verified Typescript compiler doesn't complain about wrong type anymore with AmazonPersonalizeProvider specific event type

#### Checklist
- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/analytics/src/types/Analytics.ts [hunk 1]
```diff
@@ -92,3 +92,11 @@ export interface AnalyticsEvent {
 	metrics?: EventMetrics;
 	immediate?: boolean;
 }
+
+export interface PersonalizeAnalyticsEvent {
+	eventType?: 'Identify' | 'MediaAutoTrack';
```
Comment (ashika01) [inline packages/analytics/src/types/Analytics.ts:97]: non-blocking: I think this would make good candidate for ENUM

**Review by ashika01 — APPROVED** [review]
LGTM 👍

File: packages/analytics/src/types/Analytics.ts [hunk 2]
```diff
@@ -92,3 +92,16 @@ export interface AnalyticsEvent {
...
 	immediate?: boolean;
 }
+
+export enum PersonalizeAnalyticsEventTypes {
+	IDENTIFY = 'Identify',
+	MEDIA_AUTOTRACK = 'MediaAutoTrack',
+}
+
+export interface PersonalizeAnalyticsEvent {
+	eventType?: 'Identify' | 'MediaAutoTrack' | PersonalizeAnalyticsEventTypes;
```
Comment (cshfang) [inline packages/analytics/src/types/Analytics.ts:102]: It seems a little redundant to have the strings and the enums for those exact strings. It's debatable which is preferable (specified string values vs enums) - I think it's just best for us to be _consistent_ across our typings - but we probably do not need both.

**Review by stocaaro — APPROVED** [review]

File: packages/analytics/src/types/Analytics.ts (hunk 1 above)
Comment (jamesaucode) [reply packages/analytics/src/types/Analytics.ts]: Just for this PR specifically, I'm going to go back to string unions for now because it could be breaking for some TS users. (Typescript does not know a certain string is a value inside the enum) So if I make an enum of type `PersonalizeAnalyticsEventType`, current users will see an error `'Identify' is not of type 'PersonalizeAnalyticsEventType'.`

Comment (jamesaucode) [reply packages/analytics/src/types/Analytics.ts]: I agree that we should setting some sort of guidelines on string unions vs `enum` (or `const enum`) 😄

**Review by cshfang — APPROVED** [review]
