### PR TITLE
fix(@aws-amplify/core): Support clock skew

### LINKED ISSUE #3567: API.get Sometimes  gets 403.
**Describe the bug**
Suddenly the response of API.get gets 403. (signature doesn't match)
After once I got 403, I keep getting 403 ever.
It happens sometimes, I mean few times a day.
I researched about this problem.
I noticed header is different with success one and failed one.

***difference***
- existing of host
- actually `Accept` but in below example , these are same, because I specified clearly.

***success one***
```
{  
   'User-Agent':'aws-amplify/1.0.28 react-native',
   Accept:'application/json',
   host:'***MASK***',
   'x-amz-date':'20190701T022854Z',
   'X-Amz-Security-Token':'***MASK***',
   Authorization:'AWS4-HMAC-SHA256 Credential=***MASK***/20190701/us-east-1/execute-api/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-date;x-amz-security-token, Signature=05bb4d19eae6fafbdf1e478a38010745cf0862c78fe962f672dc7e2bf5b03456'
}
```

***failed one***
```
{  
   Accept:'application/json',
   'User-Agent':'aws-amplify/1.0.28 react-native',
   'x-amz-date':'20190701T022729Z',
   'X-Amz-Security-Token':'***MASK***',
   Authorization:'AWS4-HMAC-SHA256 Credential=***MASK***/20190701/us-east-1/execute-api/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-date;x-amz-security-token, Signature=c233e9ec17f1522006a2f3d29a28160b81ce184cee806a10f039f1c3f0dcee85'
}
```

**To Reproduce**
1. I call API like this.
```
    const path = `MASK`;
    const option = {
      headers: { Accept: 'application/json' }
    };
    const res = await API.get('MASK', path, option);
```
2. Keep using app, but I don't know when it is occurred.
3. Suddenly a API.get failed.

**Expected behavior**
I expect that same request generates same request header.
And it works correctly.

**Screenshots**
No screenshots.

**Smartphone (please complete the following information):**
 - Device: HUAWEI ANE-LX2J
 - OS: Android 9
 - Browser React Native
 - Version React Native 0.59.8

**Additional context**
Nothing special.

**Sample code**
```
    const path = `MASK`;
    const option = {
      headers: { Accept: 'application/json' }
    };
    const res = await API.get('MASK', path, option);
```

### PR DESCRIPTION
**Pull request by ericclemmons**
_Issue #, if available:_ Fixes #3567 with help from @thiagohirata in #4251 

_Description of changes:_

When reviewing @thiagohirata's PR (#4251) with the team, we learned that **the `AWS` export will be removed** in the near future.

So that `Signer.ts` honors clock skew, this PR introduces `DateUtils` for setting clock skew by embedding [`getDate()` from `aws-sdk`](https://github.com/aws/aws-sdk-js/blob/6edf586dcc1de7fe8fbfbbd9a0d2b1847921e6e1/lib/util.js#L262-L277)

Users will be able to adjust this value in a backwards-compatible way via:

```js
import { DateUtils } from "amplify"

DateUtils.setClockOffset(CLOCK_OFFSET);
```

Internally, `Signer.ts` replaces calls to `new Date()` with `DateUtils.getDateWithClockOffset()`.

Type annotations:
> Screen Shot 2020-02-06 at 10 27 06 AM
> Screen Shot 2020-02-06 at 10 36 04 AM
> Screen Shot 2020-02-06 at 10 36 40 AM

This creates an opening for Amplify to automatically adjust clock-skew on users' behalf in the future.

Closes #4251 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/core/src/Util/Date.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ * Date & time utility functions to abstract the `aws-sdk` away from users.
+ * (v2 => v3 modularization is a breaking change)
+ *
+ * @see https://github.com/aws/aws-sdk-js/blob/6edf586dcc1de7fe8fbfbbd9a0d2b1847921e6e1/lib/util.js#L262
+ */
+
+const DateUtils = {
+	clockOffset: 0,
+
+	getDateWithClockOffset() {
```
Comment (ericclemmons) [inline packages/core/src/Util/Date.ts]: `aws-sdk` calls this `getDate()`, but I opted for clarity within consumers, since `getDate()` is ambiguous.

File: packages/core/src/Util/index.ts [hunk 2]
```diff
@@ -1,3 +1,4 @@
 export * from './Retry';
 export { default as Mutex } from './Mutex';
 export { default as Reachability } from './Reachability';
+export * from './DateUtils';
```
Comment (ericclemmons) [inline packages/core/src/Util/index.ts]: This becomes available as `import { DateUtils } from "amplify"`

File: packages/core/src/Util/Date.ts [hunk 3]
```diff
@@ -0,0 +1,28 @@
+/**
+ * Date & time utility functions to abstract the `aws-sdk` away from users.
+ * (v2 => v3 modularization is a breaking change)
+ *
+ * @see https://github.com/aws/aws-sdk-js/blob/6edf586dcc1de7fe8fbfbbd9a0d2b1847921e6e1/lib/util.js#L262
+ */
+
+const DateUtils = {
+	clockOffset: 0,
```
Comment (Amplifiyer) [inline packages/core/src/Util/Date.ts]: We should update either in variable name or in JSDoc that this is in secs or millis for clarity.

Comment (ericclemmons) [reply packages/core/src/Util/Date.ts]: a546192c47ea6dedadcb469b65d225b19ba6c353 seems to do the trick for typeScript, but let me know if it should be full-blown JSDoc.

> Screen Shot 2020-02-06 at 10 27 06 AM

**Comment by houmark** [comment]
Thanks @ericclemmons! This looks promising.

> Users will be able to adjust this value in a backwards-compatible way via:
> 
> ```js
> import { DateUtils } from "amplify"
> 
> DateUtils.setClockOffset(CLOCK_OFFSET);
> ```

Can you confirm that:
`import { DateUtils } from "amplify"`

should actually be:
`import { DateUtils } from "@aws-amplify"`

It'd be great with an example on how to use this in a normal use case for example in a React component.

> This creates an opening for Amplify to automatically adjust clock-skew on users' behalf in the future.

Is there a particular reason for not making it default now? For developers using Amplify, realizing that this is in fact a problem affecting their app/platform, that typically starts with getting random user reports with 403 errors, to realizing the exact reason for the error seems long and painful. This should at least be documented.

**Comment by ericclemmons** [comment]
@houmark Whoops, I mistyped the sample above. It now reads:

```js
import { DateUtils } from "aws-amplify"
// or
import { DateUtils } from "@aws-amplify/core"
```

You're exactly right: now that we have the API in place, we'll be working on handling this automatically.  The level of effort is higher than this PR, so we wanted to get it in customers' hands sooner.

I shared my notes on how I've been reproducing the clock skew errors here:
> https://github.com/aws-amplify/amplify-js/issues/2014#issuecomment-583565431

The next steps are to get `API` (and all categories) to handle this automatically.

I'll report back if I find new ways of leveraging this API on your own.  Until then, a couple customers noted their solutions here:

- https://github.com/aws-amplify/amplify-js/pull/4251#issuecomment-568915659
- https://github.com/aws-amplify/amplify-js/pull/4251#issuecomment-557185213

Thanks @houmark for staying on top of this & working with me on it!

**Comment by houmark** [comment]
Thanks @ericclemmons!

Sorry for my ignorance, but I'm still a bit confused about how to use this particular fix in for example a React component.

I have a component that is doing an unAuth'ed GraphQL query, so it's using authMode `AWS_IAM` where this is a problem. Will calling `DateUtils.setClockOffset(CLOCK_OFFSET);` at the start of the component correct the clock skew, so once the `API.graphql` runs, it will work even for users with clock being off?

Do you know when you'll be releasing `aws-amplify` again?

**Comment by dorsegal** [comment]
@houmark I have just tested amplify 2.2.4 with DateUtils.setClockOffset(CLOCK_OFFSET) at the start of our application and it looks good.
You can test it yourself by changing your client clock and make an API call

**Comment by ericclemmons** [comment]
@dorsegal What method are you using for computing the `CLOCK_OFFSET`?  We have some work to do to automate this within our categories, but it'd be great to keep a list of how customers are handling this until then.

**Comment by dorsegal** [comment]
> @dorsegal What method are you using for computing the `CLOCK_OFFSET`? We have some work to do to automate this within our categories, but it'd be great to keep a list of how customers are handling this until then.

https://github.com/aws-amplify/amplify-js/pull/4251#issuecomment-568915659

**Comment by ericclemmons** [comment]
@dorsegal Ah, thanks!  We were testing out that method, but have to dig more into internals to support the "logged out" scenario: where a user can't even sign in due to clock skew.

**Comment by Jun711** [comment]
@ericclemmons @dorsegal @houmark 

1)
To fix clock skew for non-logged in users using DateUtils.setClockOffset, we can do this. It worked for both logged-in and non-logged-in users. 

```
import Auth from '@aws-amplify/auth';
import { DateUtils } from '@aws-amplify/core';

Auth.currentUserCredentials()
.then(cred => {
  console.log('amplify currentUserCredentials ', cred);
  console.log('amplify currentUserCredentials ', cred['cognito']);
  console.log('amplify currentUserCredentials ', cred['cognito']['config']['systemClockOffset']);
  DateUtils.setClockOffset(cred['cognito']['config']['systemClockOffset']);
})
```

2)
In aws-sdk.js, there are functions to handle clockSkew: `getSkewCorrectedDate`, `applyClockOffset` and `isClockSkewed`, why doesn't Amplify use / adopt `aws-sdk.js` available methods to fix clock skew? 


## Automate Clock Skew Fix Attempt
3)
Furthermore, In aws-sdk.js, there is CognitoIdentityCredentials class that takes ConfigurationOptions as argument. There is this option `correctClockSkew` in `ConfigurationOptions` class.

Using DateUtils, I tested locally by changing js files(Credentials.js in @aws-amplify/auth) in node_modules and it seemed to work.
Changes can be seen here -> https://github.com/Jun711/aws-amplify/commit/421a0405893b19ad2d78d02795965aa142879742 

```
credentials = new AWS.CognitoIdentityCredentials({
  IdentityPoolId: identityPoolId,
  IdentityId: identityId ? identityId : undefined,
}, {
  region: region,
  correctClockSkew: true
});
```

4. 
How can I link amplify library locally and test with my changes? 
I followed the steps listed here https://github.com/aws-amplify/amplify-js/wiki/Local-Development#other-tips: 
```
yarn build
yarn link-all
```
During `yarn link-all` in aws-amplify folder, there is this `error No registered package found called` for all the packages.
```
yarn link-all                           aws-amplify git:(clockdrift) 12:37pm
yarn run v1.19.2
$ yarn unlink-all && lerna exec --parallel yarn link
$ lerna exec --parallel --bail=false yarn unlink
lerna notice cli v3.20.2
lerna info versioning independent
lerna info Executing command in 19 packages: "yarn unlink"
@aws-amplify/analytics: error No registered package found called "@aws-amplify/analytics".
@aws-amplify/analytics: info Visit https://yarnpkg.com/en/docs/cli/unlink for documentation about this command.
@aws-amplify/api: error No registered package found called "@aws-amplify/api".
...
lerna ERR! Received non-zero exit code 1 during execution
lerna success exec Executed command in 19 packages: "yarn unlink"
error Command failed with exit code 1.
```
in my project folder, I ran `yarn link aws-amplify @aws-amplify/api @aws-amplify/auth @aws-amplify/pubsub` and got this output
```
yarn link v1.19.2
error No registered package found called "aws-amplify".
info Visit https://yarnpkg.com/en/docs/cli/link for documentation about this command.
```

**Comment by Jun711** [comment]
@ericclemmons 
What is Amplify recommended way to adjust clockOffset for not logged in users?

**Comment by KevinToala** [comment]
I also have the same problem.
How can I get CLOCK_OFFSET for users who have not started? I use cognito hosted ui with amplify to login with facebook and google
