### PR TITLE
Fix Storage.put SSE-c bug

### LINKED ISSUE #8346: SSE-C Customer provided encryption key
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Storage

### Amplify Categories

storage, api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.96 GB / 15.92 GB
  Binaries:
    Node: 15.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.66)
    Internet Explorer: 11.0.19041.1
  npmGlobalPackages:
    npm: 7.9.0
    react-devtools: 4.8.2
    react-native-cli: 2.0.1
    serverless: 2.6.0

```

</details>

### Describe the bug

When specifying SSE-C (Server Side Encryption with Customer provided key) for the "Storage.Put" options, the current code requires you to add "serverSideEncryption: 'AES256'" yet the AWS specifications do not require this.  Specifying this option adds the following header to the request: "x-amz-server-side-encryption" = AES256 along with the rest of the headers needed for SSE-C: (as an example)
"x-amz-server-side-encryption-customer-algorithm" = AES256;
"x-amz-server-side-encryption-customer-key" = "at1TMx82nEy7SoAK8jHYanMQDVZMSLayXaaUvTc6CP0=";
"x-amz-server-side-encryption-customer-key-MD5" = "LWkBoT3psNdTYez70TVHUQ==";

which returns the following error as a response:
"Server Side Encryption with Customer provided key is incompatible with the encryption method specified"

Within AWSS3Provider.js, I commented out line 259 so that this header value is not populated as a test to verify.

                        if (serverSideEncryption) {
                            //params.ServerSideEncryption = serverSideEncryption;
                            if (SSECustomerAlgorithm) {
                                params.SSECustomerAlgorithm = SSECustomerAlgorithm;
                            }
                            if (SSECustomerKey) {
                                params.SSECustomerKey = SSECustomerKey;
                            }
                            if (SSECustomerKeyMD5) {
                                params.SSECustomerKeyMD5 = SSECustomerKeyMD5;
                            }
                            if (SSEKMSKeyId) {
                                params.SSEKMSKeyId = SSEKMSKeyId;
                            }
                        }
 
and using the following call:

        const result = await Storage.put(selectedNode.item.key + file.name, file, {
        level: 'private',
        serverSideEncryption: 'AES256',
        SSECustomerAlgorithm: 'AES256',
        SSECustomerKey: '12345678901234567890123456789012',
        SSECustomerKeyMD5: '767179c7a2bff19651ce97d294c30cfb'
        });    

Doing so worked and I was able to verify that the file was properly encrypted when uploaded.

### Expected behavior

I should either be using AWS managed encryption or customer provided key encryption.  However, the code assumes I am always using server side encryption with AWS via stored keys or KMS.

### Reproduction steps

1. Install Amp
2. Configure Storage
3. Call API to put a file in S3 with customer provided key.
4. You must add "serverSideEncryption: 'AES256' as an option.  Doing so will produce the error message.

### Code Snippet

```javascript
// Put your code below this line.

```
        const result = await Storage.put(selectedNode.item.key + file.name, file, {
        level: 'private',
        serverSideEncryption: 'XYZ',  // <-- arbitrary value with AWSS3Provider modified to not add the SSE header
        SSECustomerAlgorithm: 'AES256',
        SSECustomerKey: '12345678901234567890123456789012',
        SSECustomerKeyMD5: '767179c7a2bff19651ce97d294c30cfb'
        });    

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

_No response_

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by jamesaucode**
#### Description of changes
- Allow SSE-C without the `ServerSideEncryption` parameter for `.put`.
- Correctly passes SSE params to the `.get` request

#### Issue #, if available
fixes #8346

#### Description of how you validated changes
Tested on a sample app + added integration tests

#### Checklist
- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/storage/src/providers/AWSS3ProviderManagedUpload.ts [hunk 1]
```diff
@@ -176,13 +176,17 @@ export class AWSS3ProviderManagedUpload {
...
 							PartNumber: part.partNumber,
 							Body: part.bodyPart,
 							UploadId: uploadId,
-							Key: this.params.Key,
-							Bucket: this.params.Bucket,
+							Key,
+							Bucket,
+							...(this.params.SSECustomerAlgorithm && { SSECustomerAlgorithm }),
+							...(this.params.SSECustomerKey && { SSECustomerKey }),
+							...(this.params.SSECustomerKeyMD5 && { SSECustomerKeyMD5 })
```
Comment (manueliglesias) [inline packages/storage/src/providers/AWSS3ProviderManagedUpload.ts:189]:
```suggestion
							...(SSECustomerAlgorithm && { SSECustomerAlgorithm }),
							...(SSECustomerKey && { SSECustomerKey }),
							...(SSECustomerKeyMD5 && { SSECustomerKeyMD5 })

```

**Review by manueliglesias — APPROVED** [review]
LGTM 👍
