### PR TITLE
fix(@aws-amplify/auth): correctly throw the error when the refresh token is expired

### LINKED ISSUE #1468: Expired RefreshToken is not handled properly
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
If you enter a page with expired credentials (expired refresh and access token). The error returned from AWS is swallowed and the user is handled as if they are logged in. Also, there is rather odd concurrency in `Auth.currentUserPoolUser` as `CognitoUser.getSession` and `Cognito.getUserData` are called in parallel. This results in user data being requested although it should already be known that this will fail as the credentials are expired.

**What is the expected behavior?**
An exception should be re-thrown or the exception should be properly processed.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
1.0.5 (did not work in previous versions, this is a follow up to #1289 and #1303)

**You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.**
```
ConsoleLogger.js:84 [DEBUG] 43:33.470 AuthClass - configure Auth
ConsoleLogger.js:100 {[DEBUG] 43:33.470 Parser - parse config: Array(3)}
ConsoleLogger.js:84 [DEBUG] 43:33.475 AuthClass - getting current authenticted user
ConsoleLogger.js:84 [DEBUG] 43:33.476 AuthClass - cannot load federated user from auth storage
ConsoleLogger.js:84 [DEBUG] 43:33.476 AuthClass - get current authenticated userpool user
ConsoleLogger.js:100 {[DEBUG] 43:33.482 AuthClass - getting user data failed: Error: User is not authenticated
    at CognitoUser.getUserData (http://localhost:3000/static/js/bun…}
ConsoleLogger.js:84 [DEBUG] 43:33.746 AuthClass - Getting current session
ConsoleLogger.js:100 {[DEBUG] 43:33.768 AuthClass - getting user data failed: Error: User is not authenticated
    at CognitoUser.getUserData (http://localhost:3000/static/js/bun…}
ConsoleLogger.js:100 {[DEBUG] 43:33.770 AuthClass - Getting the session from this user:: CognitoUser}
localhost/:1 POST https://cognito-idp.eu-central-1.amazonaws.com/ 400 ()
ConsoleLogger.js:100 {[DEBUG] 43:34.221 AuthClass - Failed to get the user session: {…}}
localhost/:1 POST https://cognito-idp.eu-central-1.amazonaws.com/ 400 ()
ConsoleLogger.js:100 {[DEBUG] 43:34.310 AuthClass - Failed to get the user session: {…}}
localhost/:1 POST https://cognito-idp.eu-central-1.amazonaws.com/ 400 ()
ConsoleLogger.js:100 {[DEBUG] 43:34.331 AuthClass - Failed to get the session from user: CognitoUser}
ConsoleLogger.js:100 {[DEBUG] 43:34.333 AuthClass - Failed to get the current session: {…}}
:3000/#/customers:1 Uncaught (in promise) {code: "NotAuthorizedException", name: "NotAuthorizedException", message: "Refresh Token has expired"}
```

### PR DESCRIPTION
**Pull request by powerful23**
*Issue #, if available:*
fixes #1468 
*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/auth/src/Auth.ts [hunk 1]
```diff
@@ -864,37 +864,37 @@ export default class AuthClass {
                         rej(err); 
                         return;
                     }
-                });
+
```
Comment (yuth) [inline packages/auth/src/Auth.ts]: Can we add a unit test that ensures the these functions are not called concurrently

File: packages/auth/__tests__/auth-unit-test.ts [hunk 2]
```diff
@@ -1965,15 +1965,19 @@ describe('auth unit test', () => {
                     return callback('err', null);
                 });
 
-            expect.assertions(1);
+            const spyon3 = jest.spyOn(CognitoUser.prototype, 'getUserData');
+
+            expect.assertions(2);
             try {
                 await auth.currentUserPoolUser();
             } catch (e) {
```
Comment (yuth) [inline packages/auth/__tests__/auth-unit-test.ts]: This test should be re-written to use [`expect().toThrow`](https://jestjs.io/docs/en/expect#tothrowerror). The tests are more readable with this change

Comment (powerful23) [reply packages/auth/__tests__/auth-unit-test.ts]: The test will fail when using `toThrow` to catch a rejection. I followed the suggestion in this thread: https://github.com/facebook/jest/issues/1377#issuecomment-259851233
