### PR TITLE
fix(@aws-amplify/ui-components): handle slotted elements properly

### LINKED ISSUE #7241: AmplifyTotpSetup component renders broken image for QR code
**Describe the bug**
The QR Code image for TOTP Setup fails to render if `AmplifyTotpSetup` is used in `AmplifyAuthenticator`

**To Reproduce**

1. Create auth flow with `<AmplifyAuthenticator >...</AmplifyAuthenticator>`
2. Add `<AmplifyTotpSetup slot="totp-setup" />` child
3. Register a new user or sign in with one that still needs TOTP Setup
4. View broken qr code...

**Expected behavior**
QR Code renders correctly with no overrides, with issuer override, with header text override, etc

**Code Snippet**
```
import React from "react";
import "./App.css";
import Amplify from "aws-amplify";
import {
  AmplifyAuthenticator,
  AmplifySignOut,
  AmplifyTotpSetup,
} from "@aws-amplify/ui-react";
import { AuthState, onAuthUIStateChange } from "@aws-amplify/ui-components";
import awsconfig from "./aws-exports";

Amplify.configure(awsconfig);

const AuthStateApp: React.FunctionComponent = () => {
  const [authState, setAuthState] = React.useState<AuthState>();
  const [user, setUser] = React.useState<object | undefined>();

  React.useEffect(() => {
    return onAuthUIStateChange((nextAuthState, authData) => {
      setAuthState(nextAuthState);
      setUser(authData);
    });
  }, []);

  return authState === AuthState.SignedIn && user ? (
    <div className="App">
      <div>Hello, {(user as any).username}</div>
      <AmplifySignOut />
    </div>
  ) : (
    <AmplifyAuthenticator >
      <AmplifyTotpSetup headerText="My Custom TOTP Setup Text" slot="totp-setup" />
    </AmplifyAuthenticator>
  );
};

export default AuthStateApp;
```

**Screenshots**

Working if you don't use the `AmplifyTotpSetup` component:
image

Broken with no overrides `<AmplifyTotpSetup slot="totp-setup" />`
image

Broken with overrides `<AmplifyTotpSetup headerText="My Custom TOTP Setup Text" slot="totp-setup" />`
image

### PR DESCRIPTION
**Pull request by wlee221**
_Issue #, if available:_ Fixes #7241, #7406

_Description of changes:_ Handles custom implementation of slottable elements properly.

**Problem**

`amplify-authenticator` provides auth subcomponents that can be overridden custom implementation. This hasn't really been working for two reasons:

1) Custom component gets connected to DOM *as soon as* amplify-authenticator loads.

Normally, auth subcomponents render *after* a proper `authStateChange` occurs. But slotted element connected immediately. Although invisible, it still calls its lifecycle hooks where it runs setups. This breaks auth subcomponents that depends on `user` prop, because `user` is only defined after proper `authStateChange` is run.

2) Even when an element is slotted, the default one is still in the DOM along with the custom one!

Although the overridden element is hidden, it still remains in DOM and calls all the lifecycle methods as usual, on chrome. Hence there exist duplicate components, and results in race condition when they the same resource / API. (e.g. duplicate `amplify-setup-totp` calling `Auth.setupTOTP fails with concurrency exception).

This is a big problem across all auth subcomponents. Customer reports:
- `amplify-require-new-password`: #7406
- `amplify-setup-totp`: #7241 

**Solution**
1. To resolve premature DOM connection, we use the `watch` decorator to run setup when prop it needs is changed or available.
2. To resolve duplicate components, we do not render the auth subcomponent if it has been slotted. Instead, we just render a named slot without content.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx [hunk 1]
```diff
@@ -135,69 +139,45 @@ export class AmplifyAuthenticator {
...
-      case AuthState.SignedIn:
-        return [<slot name="greetings"></slot>, <slot></slot>];
+        return <div>Loading...</div>;
       default:
         throw new Error(`Unhandled auth state: ${authState}`);
     }
   }
 
+  // Returns a slot containing the Auth component corresponding to the given authState
+  private getSlotWithAuthCompoent(authState: AuthState): JSXBase.IntrinsicElements {
```
Comment (sammartinez) [inline packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx:169]: Can you fix the typo please :)

Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx]: Done 👍

**Comment by wlee221** [comment]
If we decide to remove shadow dom (see [discussion](https://github.com/aws-amplify/amplify-js/discussions/7486)), problem 2 will be resolved. Problem 1 will likely be resolved too, but I'd have to confirm that since stencil's slots seem to behave differently without shadow dom.

After we drop shadow dom support, we would remove `slotIsEmpty` logic on https://github.com/aws-amplify/amplify-js/blob/a4290f0c525ce20afaec59d8a25349e2c4a0c92d/packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx#L178
and just render `<slot name={slotName}>{authComponent}</slot>`.

I think `@Watch` decorators can remain here, because user prop changes on every auth UI event and it's a good idea to run setup again because setup depends on `user` prop.

File: packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx [hunk 2]
```diff
@@ -217,9 +197,9 @@ export class AmplifyAuthenticator {
           />
         ) : null}
         {this.authState === AuthState.SignedIn ? (
-          this.renderAuthComponent(this.authState)
+          [<slot name="greetings"></slot>, <slot></slot>]
```
Comment (tjleing) [inline packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx:200]: What's the reasoning behind doing this array as opposed to two JSX lines?  I'm guessing there's a difference between this and 
```
? (
<slot name="greetings"></slot>
<slot></slot>
)
```
 that I just don't know of.

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx [hunk 3]
```diff
@@ -60,25 +66,36 @@ export class AmplifyConfirmSignUp {
...
   }
 
+  @Watch('user')
+  userHandler() {
+    this.setup();
+  }
+
+  private setup() {
+    this.userInput = this.user ? this.user.username : null;
+    this._signUpAttrs = this.user && this.user.signUpAttrs ? this.user.signUpAttrs : null;
```
Comment (tjleing) [inline packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx:94]: Looks like you _can_ do
```
this.userInput = this.user && this.user.username;
this._signUpAttrs = this.user && this.user.signUpAttrs;
```
 -- the one downside is that if the property doesn't exist, it'll be `undefined` instead of `null`, which is still falsey and would have the same behavior in an `if(!this._signUpAttrs)` statement.  The other downside is that it might be a little harder to read.

Either way, the two statements should match (i.e. both `this.user && ... ? ...` or `this.user ? ...`)!

File: packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up-interface.ts [hunk 4]
```diff
@@ -1,14 +0,0 @@
-export interface AmplifySignUpFormFooterProps {
```
Comment (tjleing) [inline packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up-interface.ts:1]: Was this just totally unused?

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx [hunk 5]
```diff
@@ -8,7 +8,13 @@ import {
 } from '../amplify-auth-fields/amplify-auth-fields-interface';
 import { NO_AUTH_MODULE_FOUND, COUNTRY_DIAL_CODE_DEFAULT } from '../../common/constants';
 import { Translations } from '../../common/Translations';
-import { AuthState, CognitoUserInterface, AuthStateHandler, UsernameAliasStrings } from '../../common/types/auth-types';
+import {
+  AuthState,
+  CognitoUserInterface,
+  AuthStateHandler,
+  UsernameAliasStrings,
+  AmplifySignUpAttributes,
```
Comment (tjleing) [inline packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx:16]: `AmplifySignUpAttributes` looks slightly out of place here compared to all of the other imported names -- to my eyes, anyways.  `CognitoUserInterface` is prefixed by `Cognito` because it's not Amplify, but everything Amplify-related should just be the feature itself imo.

File: packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx [hunk 6]
```diff
@@ -135,69 +139,45 @@ export class AmplifyAuthenticator {
...
+        return <div>Loading...</div>;
       default:
         throw new Error(`Unhandled auth state: ${authState}`);
     }
   }
 
+  // Returns a slot containing the Auth component corresponding to the given authState
+  private getSlotWithAuthComponent(authState: AuthState): JSXBase.IntrinsicElements {
+    const authComponent = this.getAuthComponent(authState);
+    const slotName = authSlotNames[authState];
```
Comment (tjleing) [inline packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx:171]: This makes me wish that the slot names were directly equal to the auth states, instead of redirected through this map...  Although it does seem like we can't change it now due to backwards compatibility.

File: packages/amplify-ui-components/src/common/types/auth-types.ts [hunk 7]
```diff
@@ -74,6 +74,14 @@ export interface CognitoUserInterface {
...
+  username: string;
+  password: string;
+  attributes?: {
+    [userAttributes: string]: string;
+  };
+}
+
 export type AuthStateHandler = (nextAuthState: AuthState, data?: object) => void;
 
 export enum MfaOption {
```
Comment (tjleing) [inline packages/amplify-ui-components/src/common/types/auth-types.ts:87]: Unrelated, but why is this one `MfaOption` when the next one is `MFATypesInterface`...

**Review by tjleing — COMMENTED** [review]
Looks good!  I don't have much on the actual logic, but I sure do have a few tangentially related comments for you 😄

File: packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx (hunk 2 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx:200]: I tried that too! But typescript was complaining with `JSX expressions must have one parent element`. Also fragments `<> ... </>`  aren't available if `jsxFragmentFactory` option is set to true. So I wrapped them in an array 😛

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx (hunk 3 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx:94]: Good point! I'll use `?` pattern in favor of `&&` for readability.

Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx:94]: It would be great if we can use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), but we would have to bump the monorepo typescript version to `>=3.7.0`  for `eslint` to parse it (eslint references the monorepo ts instead of the one in ui-components for some reason).

File: packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up-interface.ts (hunk 4 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up-interface.ts:1]: Yup 🙃

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx (hunk 5 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx:16]: You're right, good catch for code quality! Will adjust.

File: packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx (hunk 6 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx:171]: Right. https://github.com/aws-amplify/amplify-js/blob/760374ee94e740d8772db9913eebb5019d0d7c97/packages/amplify-ui-components/src/common/types/auth-types.ts#L3-L7
These values can be set to slot names instead, but this would still be a breaking change.

File: packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up-interface.ts (hunk 4 above)
Comment (tjleing) [reply packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up-interface.ts:1]: 🙃 indeed...

File: packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx (hunk 2 above)
Comment (tjleing) [reply packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx:200]: Oh that's so weird... glad you fixed it!

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx (hunk 3 above)
Comment (tjleing) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx:94]: Sounds good!

File: packages/amplify-ui-components/src/common/types/auth-types.ts (hunk 7 above)
Comment (tjleing) [reply packages/amplify-ui-components/src/common/types/auth-types.ts:87]: Probably doesn't fit in this PR, but maybe another one?

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx (hunk 3 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx:94]: On a second thought, I'm going with your code snippet because ternary operators were getting out of hand: 
`this.user ? (this.user.username ? this.user.username : null) : null`

File: packages/amplify-ui-components/src/common/types/auth-types.ts (hunk 7 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/common/types/auth-types.ts:87]: Yeah, they could be better named. Let's make a new PR for that.

**Comment by wlee221** [comment]
Thanks for the review @tjleing! Committed the suggested changes.

**Review by tjleing — APPROVED** [review]

File: packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx [hunk 8]
```diff
@@ -135,69 +139,45 @@ export class AmplifyAuthenticator {
...
-        );
+        return <amplify-totp-setup user={this.authData} />;
       case AuthState.Loading:
-        return (
-          <slot name="loading">
-            <div>Loading...</div>
-          </slot>
-        );
-      case AuthState.SignedIn:
-        return [<slot name="greetings"></slot>, <slot></slot>];
```
Comment (elorzafe) [inline packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx:195]: What happen with `greetings`?

File: packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx (hunk 2 above)
Comment (elorzafe) [inline packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx:200]: Why you had to move `greetings` here instead of `getAuthComponent` maybe I am missing something

File: packages/amplify-ui-components/src/components/amplify-totp-setup/__snapshots__/amplify-totp-setup.spec.ts.snap [hunk 9]
```diff
@@ -5,7 +5,6 @@ exports[`amplify-totp spec: Render logic -> should render a \`less than 2 mfa ty
   <mock:shadow-root>
     <amplify-form-section headertext="Scan then enter verification code" submitbuttontext="Verify Security Token">
       <div class="totp-setup">
-        <img alt="qrcode">
```
Comment (elorzafe) [inline packages/amplify-ui-components/src/components/amplify-totp-setup/__snapshots__/amplify-totp-setup.spec.ts.snap:8]: What happened with this snap?

**Review by elorzafe — COMMENTED** [review]
Looks good @wlee221, just a couple of questions before approve

File: packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx (hunk 8 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx:195]: I'll answer in the comment below.

File: packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx (hunk 2 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx:200]: `greetings` is an edge case where it has two empty slots without any contents like the other ones. This is really for the user app content after sign-in is finished, so I left it out of `getAuthComponent`.

File: packages/amplify-ui-components/src/components/amplify-totp-setup/__snapshots__/amplify-totp-setup.spec.ts.snap (hunk 9 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-totp-setup/__snapshots__/amplify-totp-setup.spec.ts.snap:8]: It's from this diff: https://github.com/aws-amplify/amplify-js/pull/7522/files#diff-af4e2f59620b5baf02e9ffff96af7f49ae65121c51335003ffff49f6a8ec4bfeL133-R141. We no longer render an image if the qr code src has been resolved yet. This has been causing broken image to show briefly before correct image appears. 

On this snap, setupTOTP doesn't run so the image no longer exists.

**Review by elorzafe — APPROVED** [review]
@wlee221 thanks!!! 🎉 🌮 🏅

File: packages/amplify-ui-components/src/components/amplify-totp-setup/amplify-totp-setup.tsx [hunk 10]
```diff
@@ -85,13 +83,17 @@ export class AmplifyTOTPSetup {
...
+      this.code = this.buildOtpAuthPath(this.user, encodedIssuer, secretKey);
       this.generateQRCode(this.code);
     } catch (error) {
-      dispatchToastHubEvent(error);
+      /**
+       * When user has slotted totp-setup and signs out, this component unfortunately still remains in DOM and calls setup
+       * whenever `user` prop updates. The problem is that `this.user` can lose its value during the execution and throw
+       * an error here. We only display toast message if this is not the case, ie. `this.user` is still present.
+       */
+      if (this.user) dispatchToastHubEvent(error);
```
Comment (wlee221) [inline packages/amplify-ui-components/src/components/amplify-totp-setup/amplify-totp-setup.tsx:96]: Just found one more bug today... Slotted `amplify-totp-setup` still remains in DOM after it has been unrendered. The problem is that `this.user` prop can update *during* the execution of setup and will dispatch an error toast message. This code detects such cases and hides this message (bc the error is from an unrendered component and hence negligible).

File: packages/amplify-ui-components/src/components/amplify-totp-setup/amplify-totp-setup.tsx [hunk 11]
```diff
@@ -36,14 +35,22 @@ export class AmplifyTOTPSetup {
...
+
+  async componentWillLoad() {
+    /**
+     * We didn't use `@Watch` here because it doesn't fire when we go from require-new-password to totp-setup.
+     * That is because `Auth.completeNewPassword` only changes `user` in place and Watch doesn't detect changes
+     * unless we make a clone.
+     */
+    this.removeHubListener = onAuthUIStateChange(authState => {
+      if (authState === AuthState.TOTPSetup) this.setup();
+    });
```
Comment (elorzafe) [inline packages/amplify-ui-components/src/components/amplify-totp-setup/amplify-totp-setup.tsx:48]: Great idea!

**Review by elorzafe — APPROVED** [review]
Thanks @wlee221 !! 🌮 🎉 🥇

**Comment by wlee221** [comment]
Thanks for all the reviews!
