### PR TITLE
fix(@aws-amplify/auth): Call replaceState before dispatchAuthEvent

### LINKED ISSUE #4822: Redirect to callback URL occurs twice when using `federatedSignIn()`
**Describe the bug**
When using `federatedSignIn()`, the cognito redirects the browser to the URL specific in the cognito app configuration (the "sign in callback url") at the point in the authorization process where the `?code=blah-blah-blah` is passed to the client.

But the redirect occurs again on the frontend on this exact page, because when Amplify finishes exchanging the code for the token, there's another redirect here: https://github.com/aws-amplify/amplify-js/blob/cf8738ac5e7961a163ce158a7383bc27f693475f/packages/auth/src/Auth.ts#L1886

What's more, this redirect occurs _after_ the sign in methods are dispatched to Hub, so that if you want to redirect again after sign in, you can't, because you'll be redirected back to the callback URL a second time.

**To Reproduce**

To reproduce, just try to do a front-end redirect after completing a social sign in:

```
// inside of a react-router component
Hub.listen("auth", ({ payload: { event, data } }) => {
  switch (event) {
  case "cognitoHostedUI":
  case "signIn":
    props.history.replace("/");
  }
});
```

It does work, however, if you use a `setTimeout`:

```
setTimeout(() => props.history.replace("/"))
```

Doing this allows you to do your own redirect from the callback URL (i.e. to a homepage) without being redirected back to the callback page. But, obviously, `setTimeout` is not at all ideal.

**Expected behavior**
Redirect should only happen once, or an event should be dispatched after the second redirect so that we can use the history API after signing in.

<details>
  <summary><strong>Environment</strong></summary>

```
 System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 69.27 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 12.1.1
  npmPackages:
    @babel/core: 7.7.4 => 7.7.4
    @svgr/webpack: 4.3.3 => 4.3.3
    @typescript-eslint/eslint-plugin: ^2.8.0 => 2.10.0
    @typescript-eslint/parser: ^2.8.0 => 2.10.0
    aws-amplify: ^2.2.2 => 2.2.2
    babel-eslint: 10.0.3 => 10.0.3
    babel-jest: ^24.9.0 => 24.9.0
    babel-loader: 8.0.6 => 8.0.6
    babel-plugin-named-asset-import: ^0.3.5 => 0.3.5
    babel-preset-react-app: ^9.1.0 => 9.1.0
    camelcase: ^5.3.1 => 5.3.1
    case-sensitive-paths-webpack-plugin: 2.2.0 => 2.2.0
    css-loader: 3.2.0 => 3.2.0
    dotenv: 8.2.0 => 8.2.0
    dotenv-expand: 5.1.0 => 5.1.0
    eslint: ^6.6.0 => 6.7.2
    eslint-config-react-app: ^5.1.0 => 5.1.0
    eslint-loader: 3.0.2 => 3.0.2
    eslint-plugin-flowtype: 3.13.0 => 3.13.0
    eslint-plugin-import: 2.18.2 => 2.18.2
    eslint-plugin-jsx-a11y: 6.2.3 => 6.2.3
    eslint-plugin-react: 7.16.0 => 7.16.0
    eslint-plugin-react-hooks: ^1.6.1 => 1.7.0
    esri-loader: ^2.13.0 => 2.13.0
    file-loader: 4.3.0 => 4.3.0
    fs-extra: ^8.1.0 => 8.1.0
    html-webpack-plugin: 4.0.0-beta.5 => 4.0.0-beta.5
    identity-obj-proxy: 3.0.0 => 3.0.0
    jest: 24.9.0 => 24.9.0
    jest-environment-jsdom-fourteen: 0.1.0 => 0.1.0
    jest-resolve: 24.9.0 => 24.9.0
    jest-watch-typeahead: 0.4.2 => 0.4.2
    mini-css-extract-plugin: 0.8.0 => 0.8.0
    optimize-css-assets-webpack-plugin: 5.0.3 => 5.0.3
    pnp-webpack-plugin: 1.5.0 => 1.5.0
    postcss-flexbugs-fixes: 4.1.0 => 4.1.0
    postcss-loader: 3.0.0 => 3.0.0
    postcss-normalize: 8.0.1 => 8.0.1
    postcss-preset-env: 6.7.0 => 6.7.0
    postcss-safe-parser: 4.0.1 => 4.0.1
    react: ^16.12.0 => 16.12.0
    react-app-polyfill: ^1.0.5 => 1.0.5
    react-dev-utils: ^10.0.0 => 10.0.0
    react-dom: ^16.12.0 => 16.12.0
    react-router-dom: ^5.1.2 => 5.1.2
    react-scripts: ^3.3.0 => 3.3.0
    resolve: 1.12.2 => 1.12.2
    resolve-url-loader: 3.1.1 => 3.1.1
    sass-loader: 8.0.0 => 8.0.0
    semver: 6.3.0 => 6.3.0
    style-loader: 1.0.0 => 1.0.0
    terser-webpack-plugin: 2.2.1 => 2.2.1
    ts-pnp: 1.1.5 => 1.1.5
    url-loader: 2.3.0 => 2.3.0
    webpack: 4.41.2 => 4.41.2
    webpack-dev-server: 3.9.0 => 3.9.0
    webpack-manifest-plugin: 2.2.0 => 2.2.0
    workbox-webpack-plugin: 4.3.1 => 4.3.1
  npmGlobalPackages:
    @sitespeed.io/throttle: 0.5.4
    ngrok: 3.2.5
    npm: 6.11.3
```

</details>

### PR DESCRIPTION
**Pull request by ericclemmons**
Fixes #4822

_There may be conflicts if #5929 depending on which lands first._

Without this change, any changes to `window.history` were immediately overridden by `Auth.ts`.

- [x] Call `window.history.replaceState` _before_ `signIn`, `cognitoHostedUI`, and `customOAuthState` events so that customers can listen to these and customize 
their `window.history.replaceState`.
- [x] Tests

  I would've used https://github.com/jest-community/jest-extended#tohavebeencalledbefore, but some of the mocks are getting `undefined` for invocation order, plus it adds an additional dependency.  Instead, I went with an explicit test to ensure invocation order (that customers depend on) matters.

### Reproducing

I updated a CRA + federated sign in app's `App.tsx` to include:

```js
Hub.listen('auth', (event) => {
	console.log('auth event', event.payload, window.location.href);

	if (event.payload.event === 'signIn') {
		window.history.replaceState({}, document.title, '#signIn');
	}
});
```

You can see before the change `#signIn` is overridden. With this PR, `#signIn` is the last entry to persist:

> dispatch-later

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/auth/__tests__/auth-unit-test.ts [hunk 1]
```diff
@@ -2775,9 +2776,26 @@ describe('auth unit test', () => {
...
+			// Mock to help assert invocation order of other spies
+			const trackSpies = jest.fn();
 			const replaceStateSpy = jest
 				.spyOn(window.history, 'replaceState')
-				.mockReturnThis();
+				.mockImplementation((stateObj, title, url) => {
+					trackSpies(
+						`window.history.replaceState(${JSON.stringify(
+							stateObj
+						)}, ${JSON.stringify(title)}, '${url}')`
```
Comment (ericclemmons) [inline packages/auth/__tests__/auth-unit-test.ts:2787]: Doing this so the snapshot is cleaner (and fewer lines).

File: packages/auth/__tests__/auth-unit-test.ts [hunk 2]
```diff
@@ -2775,9 +2776,26 @@ describe('auth unit test', () => {
...
+					);
+					return this;
+				});
+			const hubSpy = jest
+				.spyOn(Hub, 'dispatch')
+				.mockImplementation((channel, { event }) =>
+					// payload.data isn't necessary for tracking order of dispatch events
+					trackSpies(
+						`Hub.dispatch('${channel}', { data: ..., event: '${event}' })`
```
Comment (ericclemmons) [inline packages/auth/__tests__/auth-unit-test.ts:2796]: Formatting so the snapshot below is fewer lines and matches what the invocation looks like.

File: packages/auth/__tests__/auth-unit-test.ts [hunk 3]
```diff
@@ -2794,6 +2812,25 @@ describe('auth unit test', () => {
...
+			    "window.history.replaceState({}, null, 'http://localhost:3000/')",
+			  ],
+			  Array [
+			    "Hub.dispatch('auth', { data: ..., event: 'signIn' })",
+			  ],
+			  Array [
+			    "Hub.dispatch('auth', { data: ..., event: 'cognitoHostedUI' })",
+			  ],
+			]
+		`);
```
Comment (ericclemmons) [inline packages/auth/__tests__/auth-unit-test.ts:2833]: Most of the calls in this test are "expect spy to be called with ...".  Order of events matter here, so I left specific tests (e.g. that the `redirectSIgnIn` value is re-used) in place so it's clear there there's symmetry in those values.
