### PR TITLE
fix(amazon-cognito-identity-js) refreshes session on cache bypass

### LINKED ISSUE #2827: currentAuthenticatedUser bypassCache true, dosesn't get the latest user information
**Describe the bug**
when assign new group to user in Cognito, and try to get group information from accessToken. The group information not update. 

```js
    Auth.currentAuthenticatedUser({
        bypassCache: true 
    }).then(authData=>{
        let groups =authData["signInUserSession"]["accessToken"]["payload"]["cognito:groups"];
    })
```

version:     "aws-amplify": "^1.1.10"

### PR DESCRIPTION
**Pull request by haverchuck**
*Issue #, if available:*
fixes #2827 

*Description of changes:*
Refreshes the session when a refresh token is present and bypassCache is true.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amazon-cognito-identity-js/src/CognitoUser.js [hunk 1]
```diff
@@ -1066,19 +1066,30 @@ export default class CognitoUser {
...
+      }, (err, latestUserData) => {
         if (err) {
           return callback(err, null);
         }
-        this.cacheUserData(userData);
-        return callback(null, userData);
+        this.cacheUserData(latestUserData);
+        const refresh = this.signInUserSession.getRefreshToken();
+        if (refresh && refresh.getToken()) {
+          this.refreshSession(refresh.getToken(), (refreshError, data) => {
```
Comment (powerful23) [inline packages/amazon-cognito-identity-js/src/CognitoUser.js]: should be `this.refreshSession(refresh, ...)` according to https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1203
