### PR TITLE
fix(@aws-amplify/auth): get the user attributes after signing in

### LINKED ISSUE #2892: Amplify Authenticator not returning "attributes" on inital login
**Describe the bug**
When logging in initially via Authenticator, the auth-info coming from authStateChange$ lacks the "attributes" node, containing user info from the Cognito-Pool.
When reloading the app (the authenticator automaticall logs the user back in) the auth-info contains the "attributes" node (along with all the custom attributes set for that cognito pool)

**To Reproduce**
1. register to the authStateChange$-observable
2. login via the authenticator
3. print the incoming auth-info

**Expected behavior**
The "attributes"-node should be present right from the very first login.

**Screenshots**
First Login (see "signedOut"-state)
initiallogin

Browser refresh (secondary [automatic] login)
secondarylogin

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 72.0.3626.121

**Sample code**
```
// AmplifyService loaded into "my" angular-session-service via DI
import { Injectable } from '@angular/core';
import { AmplifyService } from 'aws-amplify-angular';

@Injectable({
  providedIn: 'root'
})
export class SessionService {
  constructor (private amplifyService: AmplifyService) {
    this.amplifyService.authStateChange$.subscribe((authInfo) => {
      console.log(authInfo);
    });
  }
}
```

### PR DESCRIPTION
**Pull request by powerful23**
*Issue #, if available:*
fixes #2892 
*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/auth/src/Auth.ts [hunk 1]
```diff
@@ -403,9 +403,16 @@ export default class AuthClass {
...
-                    dispatchAuthEvent('signIn', user);
-                    resolve(user);
+                    try {
+                        // In order to get user attributes and MFA methods
+                        // We need to trigger currentUserPoolUser again
+                        const currentUser = await this.currentUserPoolUser();
+                        dispatchAuthEvent('signIn', user);
+                        resolve(currentUser);
+                    } catch (e) {
+                        logger.debug('Failed to get the signed in user', e);
```
Comment (manueliglesias) [inline packages/auth/src/Auth.ts]:
```suggestion
                        logger.error('Failed to get the signed in user', e);
```
