### PR TITLE
fix: if not overridden, using formFields in amplify-confirm-sign-in fields (#8254)

### LINKED ISSUE #8254: Customizing `formFields` in amplify-confirm-sign-in is not working
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages

  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 3.30 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    @babel/cli: ^7.0.0 => 7.13.16 
    @babel/core: ^7.0.0 => 7.14.0 (7.9.0, 7.12.9)
    @babel/preset-env: ^7.0.0 => 7.14.1 (7.3.4, 7.9.0)
    @babel/preset-react: ^7.0.0 => 7.13.13 (7.9.1)
    @types/blob-util:  1.3.3 
    @types/bluebird:  3.5.29 
    @types/chai:  4.2.7 
    @types/chai-jquery:  1.1.40 
    @types/jest: ^24.0.18 => 24.9.1 
    @types/jquery:  3.3.31 
    @types/lodash:  4.14.149 
    @types/minimatch:  3.0.3 
    @types/mocha:  5.2.7 
    @types/node: ^8.9.5 => 8.10.66 (15.0.2)
    @types/puppeteer: 1.3.0 => 1.3.0 
    @types/sinon:  7.5.1 
    @types/sinon-chai:  3.2.3 
    babel-loader: ^8.0.0 => 8.2.2 (8.1.0)
    bundlewatch: ^0.3.1 => 0.3.2 
    codecov: ^3.6.5 => 3.8.2 
    compression-webpack-plugin: ^1.1.3 => 1.1.12 
    cypress: ^3.2.0 => 3.8.3 
    husky: ^3.0.5 => 3.1.0 
    jest: ^24.x.x => 24.9.0 (23.6.0)
    jest-config: 24.8.0 => 24.8.0 (24.9.0, 23.6.0)
    json-loader: ^0.5.7 => 0.5.7 
    lerna: ^3.13.1 => 3.22.1 
    prettier: ^1.19.0 => 1.19.1 
    pretty-quick: ^1.11.1 => 1.11.1 
    rimraf: ^2.6.2 => 2.7.1 (3.0.2, 2.6.3, 2.2.8)
    rollup: ^0.67.4 => 0.67.4 
    rollup-plugin-commonjs: ^9.2.0 => 9.3.4 
    rollup-plugin-json: ^3.1.0 => 3.1.0 
    rollup-plugin-node-resolve: ^4.0.0 => 4.2.4 
    rollup-plugin-sourcemaps: ^0.4.2 => 0.4.2 
    rollup-plugin-typescript: ^1.0.0 => 1.0.1 
    source-map-loader: ^0.2.1 => 0.2.4 
    ts-jest: ^24.x.x => 24.3.0 
    tslint: ^5.7.0 => 5.20.1 
    tslint-config-airbnb: ^5.8.0 => 5.11.2 
    typedoc: ^0.16.9 => 0.16.11 
    typescript: ~3.6.4 => 3.6.5 (3.9.5, 3.7.7)
    uglifyjs-webpack-plugin: ^0.4.6 => 0.4.6 
    uuid-validate: ^0.0.3 => 0.0.3 
    webpack: ^4.32.0 => 4.46.0 (4.42.0)
    webpack-bundle-analyzer: ^3.3.2 => 3.9.0 
    webpack-cli: ^3.1.0 => 3.3.12 
    winston: ^3.2.1 => 3.3.3 
  npmGlobalPackages:
    npm: 6.14.12
```

</details>

### Describe the bug

Trying to customize the input type the `amplify-confirm-sign-in` results in an un-usable component, caused by the inner override of the `handleInputChange` function.

### Expected behavior

I was expecting that passing only the other fields should be enough, but now the component is not working anymore.
I'm providing a PR trying to solve the problem.

### Reproduction steps

Trying to customize the input type the `amplify-confirm-sign-in` results in an un-usable component, caused by the inner override of the `handleInputChange` function.

Here's the example code
1. Configure the amplify-authenticator component in your vue application (it's working)
2. Customize the amplify-confirm-sign-in component in this way
    ```js
    <amplify-confirm-sign-in
      slot="confirm-sign-in"
      header-text="Enter code from your Authenticator App"
      :form-fields.prop="formFields"
    />
    
    // ...
      data() {
        return {
          formFields: [
            {
              type: 'text',
              label: 'Verification codex',
              placeholder: 'Enter codex',
              required: true,
              // handleInputChange: I don't want to handle the input change here, it's already inside the amplify-confirm-sign-in component
            },
          ],
        };
      },
    ```

3. Try to enter the confirmation code after logging-in
4. Click on the "CONFIRM" button, it doesn't work anymore

### Code Snippet

```js
<amplify-confirm-sign-in
  slot="confirm-sign-in"
  header-text="Enter code from your Authenticator App"
  :form-fields.prop="formFields"
/>

// ...
  data() {
    return {
      formFields: [
        {
          type: 'text',
          label: 'Verification codex',
          placeholder: 'Enter codex',
          required: true,
          // handleInputChange: I don't want to handle the input change here, it's already inside the amplify-confirm-sign-in component
        },
      ],
    };
  },
```

### Log output

Not sure if it can be useful, but here's the log from my console

<details>

```
// Put your logs below this line

amplify-confirm-sign-in_7.entry.js?e862:120 Uncaught (in promise) TypeError: Cannot read property 'challengeName' of undefined
    at class_1.eval (amplify-confirm-sign-in_7.entry.js?e862:120)
    at step (amplify-confirm-sign-in_7.entry.js?e862:32)
    at Object.eval [as next] (amplify-confirm-sign-in_7.entry.js?e862:13)
    at eval (amplify-confirm-sign-in_7.entry.js?e862:7)
    at new Promise (<anonymous>)
    at __awaiter (amplify-confirm-sign-in_7.entry.js?e862:3)
    at class_1.confirm (amplify-confirm-sign-in_7.entry.js?e862:112)
    at HTMLFormElement.handleSubmit (amplify-confirm-sign-in_7.entry.js?e862:57)
eval @ amplify-confirm-sign-in_7.entry.js?e862:120
step @ amplify-confirm-sign-in_7.entry.js?e862:32
eval @ amplify-confirm-sign-in_7.entry.js?e862:13
eval @ amplify-confirm-sign-in_7.entry.js?e862:7
__awaiter @ amplify-confirm-sign-in_7.entry.js?e862:3
class_1.confirm @ amplify-confirm-sign-in_7.entry.js?e862:112
handleSubmit @ amplify-confirm-sign-in_7.entry.js?e862:57
```

</details>

### aws-exports.js

_No response_

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by dennybiasiolli**
Close #8254

#### Description of changes
If not overridden, using formFields in amplify-confirm-sign-in fields

#### Issue #, if available
#8254

#### Description of how you validated changes
Waiting for your approval for the suggested changes.
Let me know if you need the same changes in other components.

#### Checklist
- [X] PR description included
- [X] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dennybiasiolli** [comment]
Updated adding a few more tests

**Comment by hkjpotato** [comment]
@dennybiasiolli thank you for submitting the PR! Our team will review it asap. 

At this moment, I am checking the original issue #8254 to better understand the problem scope, and re-run your code fix to see if it introduces any unexpected side effects to the existing component/pattern.

**Comment by dennybiasiolli** [comment]
Thank you @hkjpotato , I appreciate this, let me know if I have to change something

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx [hunk 1]
```diff
@@ -112,6 +112,27 @@ export class AmplifyConfirmSignIn {
 		}
 	}
 
+	private constructFormFieldOptions(formFields: FormFieldTypes | string[]) {
+		const content = [];
+
+		if (formFields === undefined) return undefined;
```
Comment (wlee221) [inline packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:118]: Can we add `formFields.length > 0` check here? If so, we can return the default form field with just `code`.

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx [hunk 2]
```diff
@@ -112,6 +112,27 @@ export class AmplifyConfirmSignIn {
...
+
+		formFields.forEach((formField: FormFieldType | string) => {
+			if (typeof formField === 'string') {
+				content.push(formField);
+			} else {
```
Comment (wlee221) [inline packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:123]: Looks like we are assuming all the other formField items to be of type `string` though it can be `object` too. Can we handle `object` case here, too? For example, it should be able to handle

```tsx
formFields={[
  {
    type: 'username',
    label: 'Custom Username',
    placeholder: 'Custom Username Placeholder',
  },
  {
    type: 'code',
    label: 'Custom Confirmation code',
    placeholder: 'Custom Confirmation Code',
  },
]}
```

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.spec.ts [hunk 3]
```diff
@@ -25,6 +25,29 @@ describe('amplify-confirm-sign-in spec:', () => {
 		it('should render `submitButtonText` to `Confirm` by default', () => {
 			expect(confirmSignIn.submitButtonText).toEqual(Translations.CONFIRM);
 		});
+
+		it('should have default formFields by default', () => {
```
Comment (wlee221) [inline packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.spec.ts:29]: Thanks a lot for this! We can always have more testing in our ui components :)

**Review by wlee221 — CHANGES_REQUESTED** [review]
Hi @dennybiasiolli, thank you a **lot** for this PR! This is one of the inconsistencies between our auth components that haven't been fixed. I just got some minor change requests, but the PR looks good otherwise.

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx (hunk 2 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:123]: On a second look, I see why you're implementing it this way. Looks like `confirm-sign-in` only expects `code` and does not have input change handlers for other inputs. (Which makes sense because you wouldn't expect other inputs on the `confirm-sign-in`). In that case, I'm fine with this code! Resolving, sorry about the confusion!

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx (hunk 1 above)
Comment (dennybiasiolli) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:118]: Yes no problem, we might need to set a `defaultFormFields` value because the `formFields` is a props, so the user can change it externally.
In case of `undefined` it keeps the default value, but in case of other values (passed by the user) it will be overridden by the user's value.

Comment (dennybiasiolli) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:119]: Here: https://github.com/aws-amplify/amplify-js/pull/8255/commits/d7e06ae2dbca9c45b85c66160c22572f9e83c00e
😄

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.spec.ts (hunk 3 above)
Comment (dennybiasiolli) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.spec.ts:29]: I like to test everything I could :)

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx (hunk 1 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:119]: ty!

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx [hunk 4]
```diff
@@ -112,6 +113,28 @@ export class AmplifyConfirmSignIn {
...
+	private constructFormFieldOptions(formFields: FormFieldTypes | string[]) {
+		const content = [];
+
+		if (formFields === undefined) return undefined;
+		if (formFields.length <= 0) return this.defaultFormFields;
+
+		formFields.forEach((formField: FormFieldType | string) => {
+			if (typeof formField === 'string') {
+				content.push(formField);
+			} else {
```
Comment (wlee221) [inline packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:125]: To follow-up our discussion on https://github.com/aws-amplify/amplify-js/issues/8254#issuecomment-848320872, let's be more flexible in accepting different `formFields` here. The logic should look something like:

```tsx
if (content.type === 'code') {
  // This is a code input field. Attach input handler.
  content.push({
     ...formField, // `inputProps` will be passed over here.
      handleInputChange: event => this.handleCodeChange(event),
    });
} else {
  // This is either a `string`, and/or a custom field that isn't `code`. Pass this directly.
  content.push(formField);
}
```

Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:125]: Technically, `formField` can be equal to string `"code"`, but I think it's safe to assume that `formField` will be an object here as per our official documentation / support.

**Review by wlee221 — CHANGES_REQUESTED** [review]
Following up from #8254. Thanks again for your responsiveness through the thread!

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx [hunk 5]
```diff
@@ -131,7 +154,7 @@ export class AmplifyConfirmSignIn {
 						</span>
 					}
 				>
-					<amplify-auth-fields formFields={this.formFields} />
+					<amplify-auth-fields formFields={this.constructFormFieldOptions(this.formFields)} />
```
Comment (wlee221) [inline packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:157]: Last nit, can we construct `formField` once so that this doesn't run on every render? `setup` would be a good place to do so!

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx (hunk 4 above)
Comment (dennybiasiolli) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:125]: Ok perfect, I'm changing this using
```js
	if (typeof formField === 'string' || formField.type !== 'code') {
		// This is either a `string`, and/or a custom field that isn't `code`. Pass this directly.
		content.push(formField);
	} else {
		// This is a code input field. Attach input handler.
		content.push({
			...formField as FormFieldType, // `inputProps` will be passed over here.
			handleInputChange: event => this.handleCodeChange(event),
		});
	}
```
Notice I switched the `if` case, because of type checking by typescript, checking for formField.type directly could return errors in case of formField of type string

Comment (dennybiasiolli) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx]: Commit here: https://github.com/aws-amplify/amplify-js/pull/8255/commits/f2346a1f3b49a4b75a866a1c7159d0b8735b19ba

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx (hunk 5 above)
Comment (dennybiasiolli) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:157]: With this solution the component is not working anymore. Even if I use a `v-if` clause with `:user.prop` passing

```js
      <amplify-confirm-sign-in
        v-if="authState === 'confirmSignIn' && user"
        slot="confirm-sign-in"
        header-text="Enter code from your Authenticator App"
        :form-fields.prop="formFields"
        :user.prop="user"
      />
```

Comment (dennybiasiolli) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx]: Commit here: https://github.com/aws-amplify/amplify-js/pull/8255/commits/370f60b887f21a67185deb78146c627d5d4e5f10

I've added a few tests for checking the calls

**Comment by dennybiasiolli** [comment]
@wlee221 just a last note: please remember that when customizing the `amplify-confirm-sign-in` it's **mandatory** the `:user.prop` prop, otherwise the component will not work anymore.

Example:

```html
  <amplify-authenticator>
      <amplify-confirm-sign-in
        slot="confirm-sign-in"
        header-text="Enter code from your Authenticator App"
        :formFields.prop="formFields"
        :user.prop="user"
      />
  </amplify-authenticator>
```

and

```js
import { Auth } from 'aws-amplify';
import { onAuthUIStateChange } from '@aws-amplify/ui-components';

export default {
  data() {
    return {
      user: undefined,
      authState: undefined,
      formFields: [
        {
          type: 'code',
          required: true,
          inputProps: {
            type: 'text', // specify the actual html input type here
            inputmode: 'numeric',
            pattern: '[0-9]*',
            autocomplete: 'one-time-code',
            required: true,
          },
        },
      ],
    };
  },
  created() {
    this.unsubscribeAuth = onAuthUIStateChange((authState, authData) => {
      this.authState = authState;
      this.user = authData;
    });
  },
};
```

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx (hunk 4 above)
Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx]: Yeah, I think that's okay. I can't think of a use case where we need to submit more than just the `code` to Cognito, so I assume users will provide their own handler for these edge cases. If needed, we can make that adjustment later.

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx [hunk 6]
```diff
@@ -47,13 +47,14 @@ export class AmplifyConfirmSignIn {
 	 * ]
 	 * ```
 	 */
-	@Prop() formFields: FormFieldTypes | string[] = [
+	 defaultFormFields: FormFieldTypes = [
```
Comment (wlee221) [inline packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:50]: Can we add `private` here and down on `constructedFormFieldOptions`? Just a nit for the style consistency 😄

Comment (wlee221) [reply packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:50]:
```suggestion
	private defaultFormFields: FormFieldTypes = [
```

File: packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx [hunk 7]
```diff
@@ -62,6 +63,8 @@ export class AmplifyConfirmSignIn {
 	@State() loading: boolean = false;
 	/* The code value in the confirm-sign-in form */
 	@State() code: string;
+	/* The constructed form field options */
+	constructedFormFieldOptions: FormFieldTypes | string[];
```
Comment (wlee221) [inline packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx:67]:
```suggestion
	private constructedFormFieldOptions: FormFieldTypes | string[];
```

**Review by wlee221 — CHANGES_REQUESTED** [review]
These LGTM! Thanks for all the test cases and quick feedback. You're right -- we need to supply `:user.prop` to get the slot working. I'll raise an issue on documentation for that.

The code changes look solid -- I just got a minor style nit but we should be good to merge very soon! Thanks again @dennybiasiolli.

**Comment by dennybiasiolli** [comment]
@wlee221 done! Changes are made and squashed in previous commits in order to keep commit history clean 😃

**Review by wlee221 — APPROVED** [review]
LGTM! Let's get this merged 😄

**Comment by dennybiasiolli** [comment]
@wlee221 sorry for my question, is there a place where I can see when this PR goes to production? So I can update my dependencies.
At the moment I have
```
    "@aws-amplify/ui-components": "^1.3.2",
    "@aws-amplify/ui-vue": "^1.0.10",
```

Thanks!

**Comment by wlee221** [comment]
Hi, 

I believe on GitHub, you can `watch` our repository for releases:

Screen Shot 2021-06-10 at 10 20 57 AM

That being said, we haven't released in a while and it's very likely we'll make a release by next week at latest. Until then please note that you can use `yarn add aws-amplify@unstable @aws-amplify/ui-vue@unstable` to unblock yourself.

**Comment by dennybiasiolli** [comment]
Great, thanks!

**Comment by wlee221** [comment]
Ah nvm, it was just released yesterday!

**Comment by dennybiasiolli** [comment]
Awesome, it works! Thanks again!

**Comment by hannesj** [comment]
This change makes it impossible to override `handleInputChange`, which is still shown in the documentation [here](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#confirm-sign-in). My use case is to use this component, together with a separate `handleSubmit`, in order to fire a `sendCustomChallengeAnswer`, rather than a `confirmSignIn`.

**Comment by dennybiasiolli** [comment]
@hannesj I think you're right, to fix this it's possible to invert the order of these two lines: https://github.com/aws-amplify/amplify-js/pull/8255/files#diff-de87cdca396cebd58dbe51c8e8ca88fb89e7bf8b6b148d4f4395d98a8d5bf496R132-R133

Can you please open a new issue referring this PR? Then I can provide you a fix for that 😉

**Comment by dennybiasiolli** [comment]
@hannesj PR here: https://github.com/aws-amplify/amplify-js/pull/8492
