### PR TITLE
fix: require cycles in various packages

### LINKED ISSUE #4859: Object prototype may only be an Object or null
After upgrading aws-amplify on a react native expo project i got the following error:
"TypeError: Prototype value can only be an object or null"

### PR DESCRIPTION
**Pull request by andreialecu**
Fixes #4859 #5371 #4687

_Description of changes:_

There were various require cycles in the code base resulting in warnings and errors listed in the issues linked above.

Additionally, some exports were imported from `"."` which can cause additional problems with certain babel and packager setups (see https://github.com/aws-amplify/amplify-js/issues/5371#issuecomment-612474990, and https://github.com/aws-amplify/amplify-js/issues/4859#issuecomment-612460339)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andreialecu** [comment]
In order to prevent this in the future, it might make sense implementing this eslint rule:

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md

The project seems to be using `tslint` though, which is being deprecated. So a migration to `eslint` would be necessary first.

File: packages/predictions/src/Providers/AmazonAIPredictionsProvider.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import {
 	AmazonAIConvertPredictionsProvider,
 	AmazonAIInterpretPredictionsProvider,
 	AmazonAIIdentifyPredictionsProvider,
-} from '.';
+} from './index';
```
Comment (Amplifiyer) [inline packages/predictions/src/Providers/AmazonAIPredictionsProvider.ts:6]: Will this not create a cycle as well since `index.ts` imports from `AmazonAIPredictionsProvider.ts` as well

Comment (andreialecu) [reply packages/predictions/src/Providers/AmazonAIPredictionsProvider.ts]: I fixed these too
