### PR TITLE
fixes #3861 : improper promise resolution in TotpSetupComp

### LINKED ISSUE #3861: Asynchronous Auth.setPreferredMFA in verifyTotpToken
**Describe the bug**
Here the original code in aws-amplify-eact
```
verifyTotpToken() {
        if (!this.inputs) {
            logger.debug('no input');
            return;
        }
        const user = this.props.authData;
        const { totpCode } = this.inputs;
        if (!Auth || typeof Auth.verifyTotpToken !== 'function' || typeof Auth.setPreferredMFA !== 'function') {
            throw new Error('No Auth module found, please ensure @aws-amplify/auth is imported');
        }
        Auth.verifyTotpToken(user, totpCode)
            .then(() => {
                // set it to preferred mfa
                Auth.setPreferredMFA(user, 'TOTP');
                this.setState({setupMessage: 'Setup TOTP successfully!'});
                logger.debug('set up totp success!');
                this.triggerTOTPEvent('Setup TOTP', 'SUCCESS', user);
            })
            .catch(err => {
                this.setState({setupMessage: 'Setup TOTP failed!'});
                logger.error(err);
            });
    }
```
It's obvious that `Auth.setPreferredMFA(user, 'TOTP');` did not call synchronously, then it will change state immediately after the call and not care about the result even errors.

**To Reproduce**
I wrote my own `withAuthenticator` function and used TOTP.
```
export function withAuthenticator(RenderedComponent) {
    handleAuthStateChange = (state, data) => {
        Auth.getPreferredMFA(data, { bypassCache: true }).then(mfa => {
            console.log(mfa) // NOMFA because setPrefferedMFA not effect yet
        }.catch(console.log)
    }
}
```

**Expected behavior**
The `verifyTotpToken` should be changed to synchronous by waiting for `setPreferredMFA` returning the result.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version: any

**Additional context**
None.

**Sample code**
```
verifyTotpToken() {
        if (!this.inputs) {
            logger.debug('no input');
            return;
        }
        const user = this.props.authData;
        const { totpCode } = this.inputs;
        if (!Auth || typeof Auth.verifyTotpToken !== 'function' || typeof Auth.setPreferredMFA !== 'function') {
            throw new Error('No Auth module found, please ensure @aws-amplify/auth is imported');
        }
        Auth.verifyTotpToken(user, totpCode)
            .then(() => {
                // set it to preferred mfa
                return Auth.setPreferredMFA(user, 'TOTP');
           }).then(()=>{
                this.setState({setupMessage: 'Setup TOTP successfully!'});
                logger.debug('set up totp success!');
                this.triggerTOTPEvent('Setup TOTP', 'SUCCESS', user);
           }) .catch(err => {
                this.setState({setupMessage: 'Setup TOTP failed!'});
                logger.error(err);
            });
    }
`
```

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

### PR DESCRIPTION
**Pull request by ashika01**
_Issue #, if available:_ #3861 

_Description of changes:_ This  PR resolves the promise properly.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx [hunk 1]
```diff
@@ -131,10 +131,11 @@ export default class TOTPSetupComp extends Component<
 		Auth.verifyTotpToken(user, totpCode)
 			.then(() => {
 				// set it to preferred mfa
-				Auth.setPreferredMFA(user, 'TOTP');
-				this.setState({ setupMessage: 'Setup TOTP successfully!' });
-				logger.debug('set up totp success!');
-				this.triggerTOTPEvent('Setup TOTP', 'SUCCESS', user);
+				Auth.setPreferredMFA(user, 'TOTP').then(() => {
```
Comment (sammartinez) [inline packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx]: NIT: Do you believe it would be worth wild to make this a try catch?

File: packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx [hunk 2]
```diff
@@ -131,10 +131,11 @@ export default class TOTPSetupComp extends Component<
...
+					this.setState({ setupMessage: 'Setup TOTP successfully!' });
+					logger.debug('set up totp success!');
+					this.triggerTOTPEvent('Setup TOTP', 'SUCCESS', user);
+				});
```
Comment (elorzafe) [inline packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx]: In case `Auth.setPreferredMFA` is rejected is not going to be catched. it requieres a catch here
```suggestion
				}).catch(err => this.setState({ setupMessage: 'Setup TOTP failed!' }));
```

File: packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.tsx [hunk 3]
```diff
@@ -143,14 +143,16 @@ describe('TOTPSetupComp test', () => {
 			const spyon2 = jest
 				.spyOn(Auth, 'setPreferredMFA')
 				.mockImplementationOnce(() => {
-					return;
+					return new Promise((res, rej) => {
+						res();
+					});
```
Comment (Amplifiyer) [inline packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.tsx]: Can just be return Promise.resolve();

File: packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.tsx [hunk 4]
```diff
@@ -143,14 +143,16 @@ describe('TOTPSetupComp test', () => {
...
 				});
 			const spyon3 = jest.spyOn(instance, 'triggerTOTPEvent');
 
 			await instance.verifyTotpToken();
 
 			expect(spyon).toBeCalled();
-			expect(spyon2).toBeCalled();
+			await expect(spyon2).toBeCalled();
```
Comment (Amplifiyer) [inline packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.tsx]: I thought we can only use await for expect...rejects or expect...resolves. I don't think it's needed here since toBeCalled() is probably not an async method.

File: packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx (hunk 1 above)
Comment (Amplifiyer) [reply packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx]: It is wild! but +1 for async/await and the one enclosing it as well.

Comment (Amplifiyer) [reply packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx]: > NIT: Do you believe it would be worth wild to make this a try catch?

It is wild!

File: packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx (hunk 2 above)
Comment (sammartinez) [reply packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx]: I dont believe this is missing correct? Cause the below code has the `.catch`

File: packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.tsx (hunk 4 above)
Comment (ashika01) [reply packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.tsx]: await here is for the spyon2 to resolve. need to synchronize that for checking the spyon3 being called.

File: packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.tsx (hunk 3 above)
Comment (ashika01) [reply packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.tsx]: That would work too. Just going with this for consistency.

File: packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx (hunk 2 above)
Comment (ashika01) [reply packages/aws-amplify-react/src/Widget/TOTPSetupComp.tsx]: We need to catch that separately.

File: packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.tsx (hunk 4 above)
Comment (ashika01) [reply packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.tsx]: Rewrote the tests. Let me know if it looks good :)

**Comment by ashika01** [comment]
@Amplifiyer @elorzafe This PR is ready to review. 
One major issue breaking different test implementation was using `mockClear` which only clears the mock info and that caused leaks. Changing it to `mockRestore` solved the leak as they force restore to original implementation.
