### PR TITLE
fix(amazon-cognito-identity-js): add mfa setting type

### LINKED ISSUE #625: CognitoUser.prototype.setUserMfaPreference is missing from typescript index
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Method is missing.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?
The function should be exposed

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
2.0.3
You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

### PR DESCRIPTION
**Pull request by powerful23**
*Issue #, if available:*
fixes #625
*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amazon-cognito-identity-js/index.d.ts [hunk 1]
```diff
@@ -4,6 +4,11 @@ declare module "amazon-cognito-identity-js" {
 
     export type NodeCallback<E,T> = (err?: E, result?: T) => void;
 
+    export interface IMfaSettings {
+        PreferredMfa: boolean,
```
Comment (yuntuowang) [inline packages/amazon-cognito-identity-js/index.d.ts]: Why preferredMfa is boolean? Should it be string indicating whether SMS or TOTP?

Comment (yuntuowang) [reply packages/amazon-cognito-identity-js/index.d.ts]: Got it. https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SetUserMFAPreference.html
