### PR TITLE
Revert removing the identity_id from setting federated credentials

### LINKED ISSUE #5309: Auth.federatedSignIn() : NotAuthorizedException: Invalid login token. Can't pass in a Cognito token
**Describe the bug**
This code was previously working with aws-amplify@^2.2.6; on upgrade to aws-amplify@^3.0.5 the call to `Auth.federatedSignIn` now throws an error `NotAuthorizedException: Invalid login token. Can't pass in a Cognito token.`

auth_token generated server-side...
```
const params: CognitoIdentity.GetOpenIdTokenForDeveloperIdentityInput = {
  IdentityPoolId: config.get('aws.cognito.identitypoolid'),
  Logins: loginsMap,
};
cognitoidentity.getOpenIdTokenForDeveloperIdentity(params, (err, data) => {
// ...error handling...
const creds: CognitoCredentials = {
  identityId: data.IdentityId,
  auth_token: data.Token
 }
```

auto_token used client-side to authenticate with Cognito.
```
public async signInWithAuthToken(authToken: string | null, refreshToken: string | null) {
  const authData = this.jwtHelper.decodeToken(authToken);
  const refreshData = this.jwtHelper.decodeToken(refreshToken);
  const federatedUser: FederatedUser = {
    name: refreshData.name,
    email: refreshData.email
  };
  const tokenResponse: FederatedResponse = {
    identity_id: authData.sub
    token: authToken,
    expires_at: authData.exp
  };
  const result = await Auth.federatedSignIn('developer', tokenResponse, federatedUser)
```

**To Reproduce**

Due to the nature of this (requires client/server) the reproduce case is more complex than I would like... the below repo is the smallest I can get it. In practice there's only two bits of code amidst the boiler plate required.

server/src/auth.ts
client/src/app/app.component.ts
https://github.com/mcroker/amplify-js-issue-5309-reproduce

**Expected behavior**

I believe the above code snippet should still work. Whilst it's clear there are breaking changes between Amplify v2 and v3. I can't see any breaking changes in the Auth changelog between 2.2.6 and 3.0.5 that cause this behaviour.

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
 System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.42 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /opt/local/bin/node
    npm: 6.13.4 - /opt/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.0.5
  npmPackages:
    @angular-devkit/architect: ^0.901.0 => 0.901.0 
    @angular-devkit/build-angular: ^0.901.0 => 0.901.0 
    @angular-devkit/core: ~9.1.0 => 9.1.0 
    @angular-devkit/schematics: ~9.1.0 => 9.1.0 
    @angular/animations: ^9.1.0 => 9.1.0 
    @angular/cdk: ^9.2.0 => 9.2.0 
    @angular/cli: ~9.1.0 => 9.1.0 
    @angular/common: ~9.1.0 => 9.1.0 
    @angular/compiler: ~9.1.0 => 9.1.0 
    @angular/compiler-cli: ~9.1.0 => 9.1.0 
    @angular/core: ~9.1.0 => 9.1.0 
    @angular/forms: ~9.1.0 => 9.1.0 
    @angular/language-service: ~9.1.0 => 9.1.0 
    @angular/localize: ^9.1.0 => 9.1.0 
    @angular/material: ^9.2.0 => 9.2.0 
    @angular/platform-browser: ~9.1.0 => 9.1.0 
    @angular/platform-browser-dynamic: ~9.1.0 => 9.1.0 
    @angular/router: ~9.1.0 => 9.1.0 
    @angular/youtube-player: ^8.2.3 => 8.2.3 
    @auth0/angular-jwt: ^4.0.0 => 4.0.0 
    @babel/core: ^7.9.0 => 7.9.0 
    @datorama/akita: ^4.22.0 => 4.22.0 
    @datorama/akita-ng-router-store: ^4.0.0 => 4.0.0 
    @datorama/akita-ngdevtools: ^4.0.0 => 4.0.0 
    @fortawesome/angular-fontawesome: ^0.6.1 => 0.6.1 
    @fortawesome/fontawesome-svg-core: ^1.2.28 => 1.2.28 
    @fortawesome/free-solid-svg-icons: ^5.13.0 => 5.13.0 
    @ionic-native/core: ^5.23.0 => 5.23.0 
    @ionic-native/facebook: ^5.23.0 => 5.23.0 
    @ionic-native/splash-screen: ^5.23.0 => 5.23.0 
    @ionic-native/status-bar: ^5.23.0 => 5.23.0 
    @ionic/angular: ^5.0.7 => 5.0.7 
    @ionic/angular-toolkit: ^2.2.0 => 2.2.0 
    @mcroker/arch-tslint: 0.0.6 => 0.0.6 
    @ngx-translate/core: ^12.1.2 => 12.1.2 
    @ngx-translate/http-loader: ^4.0.0 => 4.0.0 
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addon-notes: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/angular: ^5.3.18 => 5.3.18 
    @types/jasminewd2: ~2.0.3 => 2.0.8 
    @types/node: ^12.11.1 => 12.12.34 
    @types/youtube: 0.0.38 => 0.0.38 
    aws-amplify: ^3.0.5 => 3.0.5 
    aws-amplify-angular: ^5.0.5 => 5.0.5 
    babel-loader: ^8.1.0 => 8.1.0 
    bootstrap: ^4.4.1 => 4.4.1 
    codelyzer: ^5.1.2 => 5.2.1 
    cordova: ^9.0.0 => 9.0.0 
    cordova-ios: 5.1.1 => 5.1.1 
    cordova-plugin-device: ^2.0.3 => 2.0.3 
    cordova-plugin-facebook4: ^6.4.0 => 6.4.0 
    cordova-plugin-ionic-keyboard: ^2.0.5 => 2.2.0 
    cordova-plugin-ionic-webview: ^4.0.0 => 4.1.3 
    cordova-plugin-splashscreen: ^5.0.3 => 5.0.3 
    cordova-plugin-statusbar: ^2.4.3 => 2.4.3 
    cordova-plugin-whitelist: ^1.3.4 => 1.3.4 
    core-js: ^2.5.4 => 2.6.11 
    ionic: ^5.4.16 => 5.4.16 
    jasmine-core: ~3.4.0 => 3.4.0 
    jasmine-spec-reporter: ~4.2.1 => 4.2.1 
    jsonwebtoken: ^8.5.1 => 8.5.1 
    karma: ^4.4.1 => 4.4.1 
    karma-chrome-launcher: ~2.2.0 => 2.2.0 
    karma-coverage-istanbul-reporter: ~2.0.1 => 2.0.6 
    karma-jasmine: ~2.0.1 => 2.0.1 
    karma-jasmine-html-reporter: ^1.4.0 => 1.5.1 
    karma-junit-reporter: ^2.0.1 => 2.0.1 
    native-run: ^0.3.0 => 0.3.0 
    ng-mocks: ^9.0.0 => 9.0.0 
    protractor: ~5.4.0 => 5.4.2 
    rxjs: ~6.5.5 => 6.5.5 
    ts-node: ~7.0.0 => 7.0.1 
    tslib: ^1.10.0 => 1.10.0 
    tslint: ~5.15.0 => 5.15.0 
    typescript: ^3.5.3 => 3.8.3 
    uuid: ^3.4.0 => 3.4.0 
    webpack-bundle-analyzer: ^3.6.0 => 3.6.0 
    youtube: ^0.1.0 => 0.1.0 
    zone.js: ~0.10.2 => 0.10.3 
  npmGlobalPackages:
    @aws-amplify/cli: 4.17.2
    angular-http-server: 1.9.0
    englandrugby-gms-parser: 0.0.3
    http-server: 0.12.1
    npm: 6.13.4

```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

### LINKED ISSUE #5313: (BUG) Auth signUp give wrong error message
**Describe the bug**

Auth signUp give wrong Error information when it receives `InvalidParameterException`,

It will always show `Username could not be created. Please make sure that the username you have entered is between 1 and 128 characters.`

**aws-amplify Version**

3.0.5

**Desktop:**

OS: macOS Catalina
Node Version: v13.5.0
Project: React Native

**To Reproduce**

I created a React Native app in which I use Auth. My schema looks like this:

in `App.tsx`

```typescript
Amplify.configure({
      Auth: {
        userPoolId: "****",
        region: "****",
        userPoolWebClientId: "***",
      },
    });
```

sign up code: 

```typescript
try {
      const result = await Auth.signUp({
        username: data.username,
        password: data.password,
        attributes: {
          email: data.email, // optional
          phone_number: data.phone, // optional - E.164 number convention
          name: data.fullName,
        },
      });
      console.log(result);
    } catch (err) {
      console.log(err.message);
      throw new Error(err.message);
    }
```

**Expected behavior**

In this case, when the phone number is not in the correct format, I expect the API returns the Error msg related to the phone number format error. 

While I get `Username could not be created. Please make sure that the username you have entered is between 1 and 128 characters.` instead.

**What I found**

After I investigating the RN network request, I found the actual error in the `responseHeaders`.
```typescript
responseHeaders: {
  x-amzn-errormessage: "Invalid phone number format",
  x-amzn-errortype: "InvalidParameterException"
}
```

WechatIMG35

And I found this in the source code `amplify-js/packages/auth/src/Auth.ts` in the line 310

WX20200407-134859@2x

https://github.com/aws-amplify/amplify-js/blob/c11955da9964b681b758098bdf80078215a90bd6/packages/auth/src/Auth.ts#L310

I hope this ticket can help to fix the problem and the Auth signup should throw the actual error return from the server.

### PR DESCRIPTION
**Pull request by Amplifiyer**
_Issue #, if available:_ fixes #5309 

_Description of changes:_ While doing migration of aws-sdk to V3, we had several discussions regarding the presence of identity_id in the `_setCredentialsFromFederation()` method and we couldn't think of any use case that would warrant an identity_id. This caused us to drop the identity_id support from that method.

The related issue is the example where that code path was actually working. This PR is reversal of that [change](https://github.com/Amplifiyer/amplify-js/commit/924ade8e4a814311cb22da096e19da809b3935dc#diff-bc12c34febbccc7c5bdf9ede4f4767eb) and some small fixes as noted below:

* Revert adding "Username could not be created" user facing error which got added in modularization merge. fixes #5313 
* Remove providing empty credentials to cognito client. https://github.com/aws/aws-sdk-js-v3/issues/354#issuecomment-583114220
* Use the correct way of checking for undefined
* Some formatting changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/core/src/Credentials.ts [hunk 1]
```diff
@@ -104,8 +104,7 @@ export class CredentialsClass {
 	public refreshFederatedToken(federatedInfo) {
 		logger.debug('Getting federated credentials');
 		const { provider, user } = federatedInfo;
-		let token = federatedInfo.token;
-		let expires_at = federatedInfo.expires_at;
+		let { token, expires_at, identity_id } = federatedInfo;
```
Comment (undefobj) [inline packages/core/src/Credentials.ts:107]: Minor nit, but would there ever be a reason for `identity_id` to be reassigned? If not it could be destructured in line 106 as well.

File: packages/core/src/Credentials.ts [hunk 2]
```diff
@@ -267,7 +268,7 @@ export class CredentialsClass {
 	}
 
 	private _setCredentialsFromFederation(params) {
-		const { provider, token } = params;
+		const { provider, token, identity_id, user, expires_at } = params;
```
Comment (undefobj) [inline packages/core/src/Credentials.ts:271]: Piggybacking off my above comment, these are all now destructured as `const`. Maybe it's safe?

File: packages/core/src/Credentials.ts [hunk 3]
```diff
@@ -215,12 +217,11 @@ export class CredentialsClass {
 
 		const cognitoClient = new CognitoIdentityClient({
 			region,
-			credentials: () => Promise.resolve({} as any),
 			customUserAgent: getAmplifyUserAgent(),
 		});
 
 		let credentials = undefined;
-		if (identityId && identityId !== 'undefined') {
+		if (identityId !== undefined) {
```
Comment (undefobj) [inline packages/core/src/Credentials.ts:224]: Nice catch. I always thought the right way to do this was `typeof myvar !== "undefined"` since `typeof` is guaranteed to be a string, but it's been a while since I've done these checks.

File: packages/core/src/Credentials.ts (hunk 2 above)
Comment (Amplifiyer) [reply packages/core/src/Credentials.ts:271]: yes makes sense. Updating

File: packages/core/src/Credentials.ts (hunk 1 above)
Comment (Amplifiyer) [reply packages/core/src/Credentials.ts:107]: They are getting reassigned in lines 136-139 https://github.com/aws-amplify/amplify-js/pull/5344/files/324e97434e665184f0eeac07adbf05094e6283d5#diff-bc12c34febbccc7c5bdf9ede4f4767ebR135-R139
