### PR TITLE
fix(@aws-amplify/datastore): fix syncExpression types

### LINKED ISSUE #7088: DataStore selective sync expression syntax not working with TypeScript version 3.9.7
**Describe the bug**
Using the new DataStore selective sync expressions with TypeScript `3.9.7` as follows
```typescript
DataStore.configure({
  syncExpressions: [
    syncExpression(User, (c) => c.firstName('eq', 'Johnson'))
  ]
});
```
results in the following error:

`
TS2322: Type 'Promise<{ modelConstructor: PersistentModelConstructor<User>; conditionProducer: (condition: ModelPredicate<Readonly<{ id: string; } & Record<string, any>>> | ModelPredicate<...>) => ProducerModelPredicate<...>; }>' is not assignable to type 'SyncExpression<Readonly<{ id: string; } & Record<string, any>>>'.   Type '{ modelConstructor: PersistentModelConstructor<User>; conditionProducer: (condition: ModelPredicate<Readonly<{ id: string; } & Record<string, any>>> | ModelPredicate<...>) => ProducerModelPredicate<...>; }' is not assignable to type '{ modelConstructor: PersistentModelConstructor<Readonly<{ id: string; } & Record<string, any>>>; conditionProducer: ProducerModelPredicate<Readonly<{ ...; } & Record<...>>> | (() => ProducerModelPredicate<...>); }'.     Types of property 'conditionProducer' are incompatible.       Type '(condition: ModelPredicate<Readonly<{ id: string; } & Record<string, any>>> | ModelPredicate<User>) => ProducerModelPredicate<User>' is not assignable to type 'ProducerModelPredicate<Readonly<{ id: string; } & Record<string, any>>> | (() => ProducerModelPredicate<Readonly<{ id: string; } & Record<string, any>>>)'.         Type '(condition: ModelPredicate<Readonly<{ id: string; } & Record<string, any>>> | ModelPredicate<User>) => ProducerModelPredicate<User>' is not assignable to type 'ProducerModelPredicate<Readonly<{ id: string; } & Record<string, any>>>'.           Type 'ProducerModelPredicate<User>' is not assignable to type 'ModelPredicate<Readonly<{ id: string; } & Record<string, any>>>'.             Property 'id' is missing in type 'ProducerModelPredicate<User>' but required in type '{ [x: string]: (operator: never, operand: never) => ModelPredicate<Readonly<{ id: string; } & Record<string, any>>>; readonly id: (operator: "ne" | "eq" | "le" | "lt" | "ge" | "gt" | "beginsWith" | "contains" | "notContains", operand: string) => ModelPredicate<...>; }'.
`

**Workaround**
Using the following syntax
```typescript
DataStore.configure({
  syncExpressions: [
    syncExpression(User, ((c) => c.firstName('eq', 'Johnson') as unknown) as ProducerModelPredicate<User>)
  ]
});
```
builds and works as expected.
**To Reproduce**

1. Setup a project according to the example provided in the documentation: https://docs.amplify.aws/lib/datastore/sync/q/platform/js#selective-sync
2. Make sure you are using TypeScript version 3.9.7
3. Try to build the app

**Expected behavior**
I should be able to use the sync expression syntax as documented with TypeScript version 3.9.7

**Code Snippet**
See the snippets in the official documentation: https://docs.amplify.aws/lib/datastore/sync/q/platform/js#selective-sync

**What is Configured?**

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Linux 5.8 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 17.11 GB / 31.33 GB
    Container: Yes
    Shell: 5.0.18 - /bin/bash
  Binaries:
    Node: 14.12.0 - /usr/bin/node
    npm: 6.14.7 - /usr/bin/npm
  Browsers:
    Firefox: 82.0
  npmPackages:
    @angular-devkit/build-angular: ^0.1000.8 => 0.1000.8 
    @angular/cli: ^10.2.0 => 10.2.0 
    @angular/common: ^10.2.1 => 10.2.1 
    @angular/compiler: ^10.2.1 => 10.2.1 
    @angular/compiler-cli: ^10.2.1 => 10.2.1 
    @angular/core: ^10.2.1 => 10.2.1 
    @angular/forms: ^10.2.1 => 10.2.1 
    @angular/language-service: ^10.2.1 => 10.2.1 
    @angular/platform-browser: ^10.2.1 => 10.2.1 
    @angular/platform-browser-dynamic: ^10.2.1 => 10.2.1 
    @angular/router: ^10.2.1 => 10.2.1 
    @angular/service-worker: ^10.2.1 => 10.2.1 
    @aws-amplify/datastore: ^2.7.0 => 2.7.0 
    @aws-amplify/ui-angular: ^0.2.15 => 0.2.15 
    @babel/compat-data: ~7.8.0 => 7.8.6 
    @ionic-native/core: ^5.29.0 => 5.29.0 
    @ionic-native/splash-screen: ^5.29.0 => 5.29.0 
    @ionic-native/status-bar: ^5.29.0 => 5.29.0 
    @ionic/angular: ^5.4.1 => 5.4.1 
    @ionic/angular-toolkit: ^2.3.3 => 2.3.3 
    @types/jasmine: ~3.3.8 => 3.3.16 
    @types/jasminewd2: ~2.0.3 => 2.0.8 
    @types/luxon: ^1.25.0 => 1.25.0 
    @types/moment-duration-format: ^2.2.2 => 2.2.2 
    @types/node: ^12.19.3 => 12.19.3 
    aws-amplify: ^3.3.5 => 3.3.5 
    aws-amplify-angular: ^5.0.34 => 5.0.34 
    codelyzer: ^5.1.2 => 5.2.2 
    core-js: ^2.5.4 => 2.6.11 
    cron-parser: ^2.16.3 => 2.16.3 
    jasmine-core: ~3.5.0 => 3.5.0 
    jasmine-spec-reporter: ~5.0.0 => 5.0.2 
    karma: ~5.0.0 => 5.0.9 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage-istanbul-reporter: ~3.0.2 => 3.0.3 
    karma-jasmine: ~3.3.0 => 3.3.1 
    karma-jasmine-html-reporter: ^1.5.0 => 1.5.4 
    luxon: ^1.25.0 => 1.25.0 
    protractor: ~7.0.0 => 7.0.0 
    rxjs: ^6.6.3 => 6.6.3 
    ts-node: ~7.0.0 => 7.0.1 
    tslib: ^2.0.3 => 2.0.3 
    tslint: ^6.1.3 => 6.1.3 
    typescript: ^3.9.7 => 3.9.7 
    zone.js: ~0.10.3 => 0.10.3 
  npmGlobalPackages:
    @angular/cli: 10.1.6
    @aws-amplify/cli: 4.31.1
    @ionic/cli: 6.12.0
    aws-cdk: 1.60.0
    node-gyp: 7.1.0
    npm: 6.14.7
    semver: 7.3.2

```
</details>

**Additional context**
(Probably) related issues:
#4827
#6349

### PR DESCRIPTION
**Pull request by iartemiev**
Fixes #7088 

Tested the following sync expressions in **TS** and **JS**. No errors and Intellisense works as expected in each case:
```js
syncExpression(User, () => {
	return (c) => c.jobTitle('eq', 'someVal');
}),
syncExpression(User, async () => {
	return (c) => c.jobTitle('eq', 'someVal');
}),
syncExpression(User, (c) => c.jobTitle('eq', 'someVal')),
```

cc @harrysolovay - let me know if you have any suggestions on how to improve the types further (: 
I would prefer to get rid of the `| undefined` [here](https://github.com/aws-amplify/amplify-js/compare/main...iartemiev:syncExpression-type-fix?expand=1#diff-11db1320cd9ef8ce406ca63de04c6f9104cb7674410c8d33fed7731155d13230R481) and [here](https://github.com/aws-amplify/amplify-js/compare/main...iartemiev:syncExpression-type-fix?expand=1#diff-11db1320cd9ef8ce406ca63de04c6f9104cb7674410c8d33fed7731155d13230R486) but couldn't figure out how to make that happen. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/datastore/src/types.ts [hunk 1]
```diff
@@ -448,21 +448,19 @@ export type DataStoreConfig = {
...
 };
 
-export type SyncExpression<T extends PersistentModel> = Promise<{
-	modelConstructor: PersistentModelConstructor<T>;
-	conditionProducer:
-		| ProducerModelPredicate<T>
-		| (() => ProducerModelPredicate<T>);
+export type SyncExpression = Promise<{
+	modelConstructor: any;
+	conditionProducer: (c?: any) => any;
```
Comment (elorzafe) [inline packages/datastore/src/types.ts:463]: Why you need to set those to `any`? It seems the issue was on the `syncExpression`?

File: packages/datastore/src/types.ts [hunk 2]
```diff
@@ -479,20 +477,28 @@ syncExpressions: [
...
+type Option<T extends PersistentModel> = Option0 | Option1<T>;
+
+type Lookup<T extends PersistentModel> = {
+	0: ProducerModelPredicate<T> | Promise<ProducerModelPredicate<T>>;
+	1: ModelPredicate<T> | undefined;
+};
+
+type ConditionProducer<T extends PersistentModel, A extends Option<T>> = (
+	...args: A
+) => A['length'] extends keyof Lookup<T> ? Lookup<T>[A['length']] : never;
```
Comment (harrysolovay) [inline packages/datastore/src/types.ts:491]: Glad this trick came in handy ;)

**Review by harrysolovay — APPROVED** [review]
Nothing glaringly-wrong or bad practice 👍 LGTM!

**Review by elorzafe — APPROVED** [review]
Thanks @iartemiev 🌮
