### PR TITLE
Empty `newFormfFields` array on rebuild

### LINKED ISSUE #8629: `AmplifyForgotPassword` UI repeats input field
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line

System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 121.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.5/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.164
    Edge: 92.0.902.55
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    @apollo/client: ^3.3.20 => 3.3.20 
    @apollo/client/cache:  undefined ()
    @apollo/client/core:  undefined ()
    @apollo/client/errors:  undefined ()
    @apollo/client/link/batch:  undefined ()
    @apollo/client/link/batch-http:  undefined ()
    @apollo/client/link/context:  undefined ()
    @apollo/client/link/core:  undefined ()
    @apollo/client/link/error:  undefined ()
    @apollo/client/link/http:  undefined ()
    @apollo/client/link/persisted-queries:  undefined ()
    @apollo/client/link/retry:  undefined ()
    @apollo/client/link/schema:  undefined ()
    @apollo/client/link/utils:  undefined ()
    @apollo/client/link/ws:  undefined ()
    @apollo/client/react:  undefined ()
    @apollo/client/react/components:  undefined ()
    @apollo/client/react/context:  undefined ()
    @apollo/client/react/data:  undefined ()
    @apollo/client/react/hoc:  undefined ()
    @apollo/client/react/hooks:  undefined ()
    @apollo/client/react/parser:  undefined ()
    @apollo/client/react/ssr:  undefined ()
    @apollo/client/testing:  undefined ()
    @apollo/client/utilities:  undefined ()
    @aws-amplify/ui-react: ^1.2.3 => 1.2.4 
    @testing-library/jest-dom: ^5.11.4 => 5.14.1 
    @testing-library/react: ^11.1.0 => 11.2.7 
    @testing-library/user-event: ^12.1.10 => 12.8.3 
    @types/jest: ^26.0.15 => 26.0.23 
    @types/node: ^12.0.0 => 12.20.15 (15.12.5)
    @types/react: ^17.0.0 => 17.0.11 
    @types/react-combine-reducers: ^1.0.0 => 1.0.0 
    @types/react-dom: ^17.0.0 => 17.0.8 
    @types/react-router-dom: ^5.1.7 => 5.1.7 
    @types/styled-components: ^5.1.10 => 5.1.10 
    aws-amplify: ^4.1.1 => 4.1.2 
    graphql: ^15.5.1 => 15.5.1 (14.0.0, 0.11.7)
    quicktype: ^15.0.260 => 15.0.260 
    react: ^17.0.2 => 17.0.2 
    react-combine-reducers: ^1.1.1 => 1.1.1 
    react-dom: ^17.0.2 => 17.0.2 
    react-icons: ^4.2.0 => 4.2.0 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 4.0.3 => 4.0.3 
    styled-components: ^5.3.0 => 5.3.0 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    swears: ^0.1.0 => 0.1.0 
    typescript: ^4.1.2 => 4.3.4 (3.2.4)
    web-vitals: ^1.0.1 => 1.1.2 
  npmGlobalPackages:
    @aws-amplify/cli: 5.1.2
    npm: 6.14.11
    yarn: 1.22.10

```

</details>

### Describe the bug

Using `AmplifyForgotPassword` react UI component repeats the input fields (it should only require one field)

I.e.

```
  <AmplifyForgotPassword
    slot="forgot-password"
    headerText="Header Test"
    formFields={[{ type: "email" }]}
  />
```

Results in: 

amp-ui-sign-in

### Expected behavior

It should only product one email input, not three.

### Reproduction steps

* "aws-amplify": "^4.1.1",
* "react": "^17.0.2",
* "@aws-amplify/ui-react": "^1.2.3",

```
<AmplifyAuthContainer>
          <AmplifyAuthenticator>
           
            <AmplifyForgotPassword
              slot="forgot-password"
              headerText="Header Text"
              formFields={[{ type: "email" }]}
            />
            
          </AmplifyAuthenticator>
        </AmplifyAuthContainer>

```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://bvodoevelzfa5c3q4gejukdlk4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "******",
    "aws_cognito_identity_pool_id": "us-east-1:d0b6abe4-c565-4b16-ad8f-b269d810aa39",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_reNumZDm5",
    "aws_user_pools_web_client_id": "1odf8h7epf0kjjn019vnv732p7",
    "oauth": {}
};

export default awsmobile;

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by wlee221**
#### Description of changes

Empties `newFormFields` whenever we call `buildFormFields` so that we don't add duplicate fields.

#### Issue #, if available

Closes #8629.

#### Description of how you validated changes
Validated with local linking.

Not sure why this isn't very reproducible on 1.2.7 (likely some nuance of when these components get re-rendered based on the `newFormFields`), but I confirmed internally that this patch prevents the array from getting duplicate entries.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-ui-components/src/components/amplify-forgot-password/amplify-forgot-password.tsx [hunk 1]
```diff
@@ -255,7 +256,11 @@ export class AmplifyForgotPassword {
 		this.loading = true;
 		try {
 			const { userInput, code, password } = this.forgotPasswordAttrs;
-			const data = await Auth.forgotPasswordSubmit(userInput.trim(), code, password);
+			const data = await Auth.forgotPasswordSubmit(
+				userInput.trim(),
+				code,
+				password
+			);
```
Comment (wlee221) [inline packages/amplify-ui-components/src/components/amplify-forgot-password/amplify-forgot-password.tsx:263]: Just a prettier change

**Review by chrisbonifacio — APPROVED** [review]
LGTM ✅ Thank you for looking into this so quickly!
